"""Editorial bounded context (Core) — AE-0108 Phase 4 skeleton.

The editorial context owns the 7-phase carousel editorial workflow over a
carousel project. This package follows the module conventions
(``docs/architecture/module-conventions.md``, AE-0081) and ADR-0009 (Domain
Modular Monolith):

* per-module internal layers — ``domain/``, ``application/``,
  ``infrastructure/``, ``api/``;
* the **public-facade rule** — cross-module code imports ONLY from this
  package's public API (``public.py``, re-exported here);
* manual constructor injection via ``bootstrap_module`` (ADR-0009 §9);
* the Unit-of-Work boundary owned at the application layer.

Phase 4 is **behavior-preserving** (AE-0108): the carousel workflow status
language is *re-exported* from ``rag_backend.domain.constants.carousel_workflow``
(no new strings, object-identity), the carousel entities and the
``CarouselRepository`` port are *re-exported* from their legacy locations (no
physical move, object-identity shims), and no routes/ACL move. The new
``EditorialProject`` / ``EditorialWorkflow`` aggregates model the editorial
view. Routes/ACL move behind this facade in AE-0109/0110.

Cross-module consumers SHALL import from the facade only, e.g.::

    from rag_backend.modules.editorial import EditorialService, EditorialProject
"""

from rag_backend.modules.editorial.public import (
    CAROUSEL_EDITORIAL_WORKFLOW_STATUS_DRAFT,
    CAROUSEL_WORKFLOW_PHASES,
    DEFAULT_PHASE_RETRY_CAP,
    DEFAULT_REVISION_CAP_PER_PHASE,
    FINAL_REVIEW_SEND_BACK_PHASES,
    INTERRUPT_TYPE_CONTENT_REVIEW,
    INTERRUPT_TYPE_DESIGN_REVIEW,
    INTERRUPT_TYPE_FINAL_REVIEW,
    INTERRUPT_TYPE_IMAGE_REVIEW,
    INTERRUPT_TYPE_OUTLINE_REVIEW,
    INTERRUPT_TYPE_RESEARCH_REVIEW,
    PHASE_BRIEF,
    PHASE_CONTENT,
    PHASE_DESIGN,
    PHASE_FINAL_REVIEW,
    PHASE_IMAGES,
    PHASE_OUTLINE,
    PHASE_PUBLISHED,
    PHASE_RESEARCH,
    PHASE_STATUS_APPROVED,
    PHASE_STATUS_AWAITING_HUMAN,
    PHASE_STATUS_FAILED,
    PHASE_STATUS_IN_PROGRESS,
    PHASE_STATUS_PENDING,
    PHASE_STATUS_REJECTED,
    RESUME_ROUTE_SUPPORTED_ACTIONS,
    REVIEW_ACTION_APPROVE,
    REVIEW_ACTION_EDIT,
    REVIEW_ACTION_REJECT,
    REVIEW_ACTION_REVISE,
    REVIEW_ACTIONS,
    WORKFLOW_STATUS_APPROVED_FOR_PUBLISH,
    AclApprovalAdapter,
    AclOptimisticLockingAdapter,
    AclPublicReleaseAdapter,
    AclReviewerAssignmentAdapter,
    ApprovalPort,
    ApprovalState,
    CarouselProject,
    CarouselProjectWriteOwner,
    CarouselRepository,
    CarouselSlide,
    CarouselStatus,
    CarouselTheme,
    EditorialAdapters,
    EditorialModule,
    EditorialPorts,
    EditorialProject,
    EditorialProjectView,
    EditorialService,
    EditorialWorkflow,
    EditorialWorkflowHandlers,
    EngineReviewDecisionAdapter,
    EngineSourceMaterialAdapter,
    LegacyCarouselAcl,
    OptimisticLockingPort,
    PublicReleasePort,
    PublicReleaseState,
    ResearchSource,
    ResearchSourceType,
    ReviewDecisionPort,
    ReviewerAssignmentPort,
    ReviewWorkflowEngine,
    SourceMaterialPort,
    SourceSynthesisEngine,
    StartWorkflowCommand,
    WorkflowEngine,
    WorkflowStateView,
    bootstrap_module,
)

__all__ = [
    "CAROUSEL_EDITORIAL_WORKFLOW_STATUS_DRAFT",
    "CAROUSEL_WORKFLOW_PHASES",
    "DEFAULT_PHASE_RETRY_CAP",
    "DEFAULT_REVISION_CAP_PER_PHASE",
    "FINAL_REVIEW_SEND_BACK_PHASES",
    "INTERRUPT_TYPE_CONTENT_REVIEW",
    "INTERRUPT_TYPE_DESIGN_REVIEW",
    "INTERRUPT_TYPE_FINAL_REVIEW",
    "INTERRUPT_TYPE_IMAGE_REVIEW",
    "INTERRUPT_TYPE_OUTLINE_REVIEW",
    "INTERRUPT_TYPE_RESEARCH_REVIEW",
    "PHASE_BRIEF",
    "PHASE_CONTENT",
    "PHASE_DESIGN",
    "PHASE_FINAL_REVIEW",
    "PHASE_IMAGES",
    "PHASE_OUTLINE",
    "PHASE_PUBLISHED",
    "PHASE_RESEARCH",
    "PHASE_STATUS_APPROVED",
    "PHASE_STATUS_AWAITING_HUMAN",
    "PHASE_STATUS_FAILED",
    "PHASE_STATUS_IN_PROGRESS",
    "PHASE_STATUS_PENDING",
    "PHASE_STATUS_REJECTED",
    "RESUME_ROUTE_SUPPORTED_ACTIONS",
    "REVIEW_ACTIONS",
    "REVIEW_ACTION_APPROVE",
    "REVIEW_ACTION_EDIT",
    "REVIEW_ACTION_REJECT",
    "REVIEW_ACTION_REVISE",
    "WORKFLOW_STATUS_APPROVED_FOR_PUBLISH",
    "AclApprovalAdapter",
    "AclOptimisticLockingAdapter",
    "AclPublicReleaseAdapter",
    "AclReviewerAssignmentAdapter",
    "ApprovalPort",
    "ApprovalState",
    "CarouselProject",
    "CarouselProjectWriteOwner",
    "CarouselRepository",
    "CarouselSlide",
    "CarouselStatus",
    "CarouselTheme",
    "EditorialAdapters",
    "EditorialModule",
    "EditorialPorts",
    "EditorialProject",
    "EditorialProjectView",
    "EditorialService",
    "EditorialWorkflow",
    "EditorialWorkflowHandlers",
    "EngineReviewDecisionAdapter",
    "EngineSourceMaterialAdapter",
    "LegacyCarouselAcl",
    "OptimisticLockingPort",
    "PublicReleasePort",
    "PublicReleaseState",
    "ResearchSource",
    "ResearchSourceType",
    "ReviewDecisionPort",
    "ReviewWorkflowEngine",
    "ReviewerAssignmentPort",
    "SourceMaterialPort",
    "SourceSynthesisEngine",
    "StartWorkflowCommand",
    "WorkflowEngine",
    "WorkflowStateView",
    "bootstrap_module",
]
