"""API routes package initialization."""

from rag_backend.api.routes import (
    admin,
    admin_migration,
    auth,
    blog_post,
    blog_post_ai,
    blog_post_comments,
    blog_post_quality,
    blog_post_versions,
    blog_post_workflow,
    carousels,
    chat_stream,
    content_calendar,
    conversations,
    documents,
    notifications,
    personas,
    rubrics,
    search,
    sources,
    workflow_audit,
    workflow_board,
)

__all__ = [
    "admin",
    "admin_migration",
    "auth",
    "blog_post",
    "blog_post_ai",
    "blog_post_comments",
    "blog_post_quality",
    "blog_post_versions",
    "blog_post_workflow",
    "carousels",
    "chat_stream",
    "content_calendar",
    "conversations",
    "documents",
    "notifications",
    "personas",
    "rubrics",
    "search",
    "sources",
    "workflow_audit",
    "workflow_board",
]
