"""Constants for accessibility checks (QUAL-004)."""

WCAG_AA_CONTRAST_NORMAL = 4.5
WCAG_AA_CONTRAST_LARGE = 3.0

A11Y_ISSUE_MISSING_ALT = "missing_alt_text"
A11Y_ISSUE_EMPTY_ALT = "empty_alt_text"
A11Y_ISSUE_NO_HEADINGS = "no_headings"
A11Y_ISSUE_LOW_CONTRAST = "low_contrast"
A11Y_ISSUE_NO_LANG = "no_language_attribute"

A11Y_SEVERITY_ERROR = "error"
A11Y_SEVERITY_WARNING = "warning"
A11Y_SEVERITY_INFO = "info"

A11Y_SCORE_PASS = 80
A11Y_SCORE_WARN = 60

HEX_COLOR_LENGTH = 6
SRGB_THRESHOLD = 0.03928

__all__ = [
    "A11Y_ISSUE_EMPTY_ALT",
    "A11Y_ISSUE_LOW_CONTRAST",
    "A11Y_ISSUE_MISSING_ALT",
    "A11Y_ISSUE_NO_HEADINGS",
    "A11Y_ISSUE_NO_LANG",
    "A11Y_SCORE_PASS",
    "A11Y_SCORE_WARN",
    "A11Y_SEVERITY_ERROR",
    "A11Y_SEVERITY_INFO",
    "A11Y_SEVERITY_WARNING",
    "HEX_COLOR_LENGTH",
    "SRGB_THRESHOLD",
    "WCAG_AA_CONTRAST_LARGE",
    "WCAG_AA_CONTRAST_NORMAL",
]
