"""Constants for versioned carousel artifact builds."""

ARTIFACT_STAGING_DIR = ".staging"
ARTIFACT_VERSIONS_DIR = "versions"
ARTIFACT_MANIFEST_FILENAME = "artifact-manifest.json"
ARTIFACT_CURRENT_INDEX_FILENAME = "current.json"
ARTIFACT_VERSION_PREFIX = "sha256-"
ARTIFACT_VERSION_HEX_LENGTH = 64

EXPORTER_CONTRACT_VERSION = "playwright_v1"
RENDERER_CONTRACT_VERSION = "hero_lower_third_v1"

ERR_ARTIFACT_BUILD_CONFLICT = "artifact_build_conflict"
ERR_ARTIFACT_MANIFEST_MISSING = "artifact manifest missing"
ERR_ARTIFACT_MANIFEST_INVALID = "artifact manifest invalid"
ERR_ARTIFACT_MANIFEST_POLICY_MISMATCH = "artifact manifest policy mismatch"
ERR_ARTIFACT_MANIFEST_VERSION_MISMATCH = "artifact manifest version mismatch"
ERR_ARTIFACT_STAGING_INCOMPLETE = "artifact staging directory incomplete"

__all__ = [
    "ARTIFACT_CURRENT_INDEX_FILENAME",
    "ARTIFACT_MANIFEST_FILENAME",
    "ARTIFACT_STAGING_DIR",
    "ARTIFACT_VERSIONS_DIR",
    "ARTIFACT_VERSION_HEX_LENGTH",
    "ARTIFACT_VERSION_PREFIX",
    "ERR_ARTIFACT_BUILD_CONFLICT",
    "ERR_ARTIFACT_MANIFEST_INVALID",
    "ERR_ARTIFACT_MANIFEST_MISSING",
    "ERR_ARTIFACT_MANIFEST_POLICY_MISMATCH",
    "ERR_ARTIFACT_MANIFEST_VERSION_MISMATCH",
    "ERR_ARTIFACT_STAGING_INCOMPLETE",
    "EXPORTER_CONTRACT_VERSION",
    "RENDERER_CONTRACT_VERSION",
]
