"""Carousel pipeline constants —
statuses, slide types, dimensions, languages, image presets.
"""

from rag_backend.domain.constants.carousel_theme_keywords import (
    BRAND_KEYWORDS,
    THEME_CATEGORY_KEYWORDS,
)
from rag_backend.domain.constants.carousel_themes import (
    AUTO_ROTATION_THEME_KEYS,
    BRAND_PALETTES,
    CAROUSEL_THEMES,
    LIGHT_THEME_KEYS,
)

# Carousel statuses
CAROUSEL_STATUS_PENDING = "pending"
CAROUSEL_STATUS_RESEARCHING = "researching"
CAROUSEL_STATUS_DRAFTING = "drafting"
CAROUSEL_STATUS_DESIGNING = "designing"
CAROUSEL_STATUS_GENERATING_IMAGES = "generating_images"
CAROUSEL_STATUS_EXPORTING = "exporting"
CAROUSEL_STATUS_COMPLETED = "completed"
CAROUSEL_STATUS_FAILED = "failed"

VALID_CAROUSEL_STATUSES = {
    CAROUSEL_STATUS_PENDING,
    CAROUSEL_STATUS_RESEARCHING,
    CAROUSEL_STATUS_DRAFTING,
    CAROUSEL_STATUS_DESIGNING,
    CAROUSEL_STATUS_GENERATING_IMAGES,
    CAROUSEL_STATUS_EXPORTING,
    CAROUSEL_STATUS_COMPLETED,
    CAROUSEL_STATUS_FAILED,
}

# Slide types
SLIDE_TYPE_INTRO = "intro"
SLIDE_TYPE_SUMMARY = "summary"
SLIDE_TYPE_CONTENT = "content"
SLIDE_TYPE_CLOSING = "closing"
SLIDE_TYPE_CTA = "cta"

# Default aspect ratio
CAROUSEL_ASPECT_RATIO = "1080x1350"
CAROUSEL_WIDTH = 1080
CAROUSEL_HEIGHT = 1350

# Default language
CAROUSEL_DEFAULT_LANGUAGE = "pt-BR"

# Default slides config
CAROUSEL_DEFAULT_SLIDES_CONFIG = "1 intro, 1 summary, 3 content, 1 closing, 1 cta"
CAROUSEL_SLIDES_CONFIG_SEVEN = "7_slides"

# Template versions
TEMPLATE_VERSION_V1 = "v1"
TEMPLATE_VERSION_V2 = "v2"
CAROUSEL_PROMPT_VERSION_V3 = "v3"
DEFAULT_TEMPLATE_VERSION = TEMPLATE_VERSION_V2
DEFAULT_CAROUSEL_PROMPT_VERSION = "v2"

# Language codes
LANGUAGE_PT = "pt"
LANGUAGE_EN = "en"

# Swipe text
SWIPE_TEXT_PT = "Swipe \u2192"
SWIPE_TEXT_EN = "Swipe \u2192"

# Research source types
RESEARCH_SOURCE_TWITTER = "twitter"
RESEARCH_SOURCE_BLOG = "blog"
RESEARCH_SOURCE_REDDIT = "reddit"
RESEARCH_SOURCE_GITHUB = "github"
RESEARCH_SOURCE_NEWS = "news"
RESEARCH_SOURCE_DOCUMENTATION = "documentation"

VALID_RESEARCH_SOURCE_TYPES = {
    RESEARCH_SOURCE_TWITTER,
    RESEARCH_SOURCE_BLOG,
    RESEARCH_SOURCE_REDDIT,
    RESEARCH_SOURCE_GITHUB,
    RESEARCH_SOURCE_NEWS,
    RESEARCH_SOURCE_DOCUMENTATION,
}

# Image generation providers
IMAGE_MODEL_GEMINI = "gemini"
IMAGE_MODEL_OPENAI = "openai"

VALID_IMAGE_MODELS: set[str] = {IMAGE_MODEL_GEMINI, IMAGE_MODEL_OPENAI}

# Image style presets
IMAGE_STYLE_COMIC_NEON = "comic_neon"
IMAGE_STYLE_CINEMATIC = "cinematic"
IMAGE_STYLE_HYPERREAL = "hyperreal"
IMAGE_STYLE_NEO_ANIME = "neo_anime"
# Flat editorial vector preset — the light/editorial counterpart, paired with
# the light palettes (risograph, paper_editorial, clinical_mint).
IMAGE_STYLE_FLAT_EDITORIAL = "flat_editorial"

VALID_IMAGE_STYLES: set[str] = {
    IMAGE_STYLE_COMIC_NEON,
    IMAGE_STYLE_CINEMATIC,
    IMAGE_STYLE_HYPERREAL,
    IMAGE_STYLE_NEO_ANIME,
    IMAGE_STYLE_FLAT_EDITORIAL,
}

# Default combo. OpenAI (not Gemini): prod has OPENAI_API_KEY but no GEMINI_API_KEY,
# so the default preset must use a provider with a configured key (AE-0215 guard).
IMAGE_MODEL_DEFAULT = IMAGE_MODEL_OPENAI
IMAGE_STYLE_DEFAULT = IMAGE_STYLE_NEO_ANIME

# Export constants
HD_SUBDIR_NAME = "hd"
SHARED_IMAGES_DIR_NAME = "images"
SLIDE_FILENAME_PREFIX = "slide_"
SLIDE_IMAGE_EXTENSION = ".jpg"
IMAGE_FORMAT_JPEG = "JPEG"
IMAGE_FORMAT_JPEG_LOWER = "jpeg"
IMAGE_FORMAT_PNG = "PNG"
IMAGE_FORMAT_WEBP = "WEBP"

# Supported (model, style) combos
SUPPORTED_IMAGE_COMBOS: set[tuple[str, str]] = {
    (IMAGE_MODEL_GEMINI, IMAGE_STYLE_COMIC_NEON),
    (IMAGE_MODEL_OPENAI, IMAGE_STYLE_CINEMATIC),
    (IMAGE_MODEL_OPENAI, IMAGE_STYLE_HYPERREAL),
    (IMAGE_MODEL_OPENAI, IMAGE_STYLE_NEO_ANIME),
    (IMAGE_MODEL_OPENAI, IMAGE_STYLE_FLAT_EDITORIAL),
}

__all__ = [
    "AUTO_ROTATION_THEME_KEYS",
    "BRAND_KEYWORDS",
    "BRAND_PALETTES",
    "CAROUSEL_ASPECT_RATIO",
    "CAROUSEL_DEFAULT_LANGUAGE",
    "CAROUSEL_DEFAULT_SLIDES_CONFIG",
    "CAROUSEL_HEIGHT",
    "CAROUSEL_PROMPT_VERSION_V3",
    "CAROUSEL_SLIDES_CONFIG_SEVEN",
    "CAROUSEL_STATUS_COMPLETED",
    "CAROUSEL_STATUS_DESIGNING",
    "CAROUSEL_STATUS_DRAFTING",
    "CAROUSEL_STATUS_EXPORTING",
    "CAROUSEL_STATUS_FAILED",
    "CAROUSEL_STATUS_GENERATING_IMAGES",
    "CAROUSEL_STATUS_PENDING",
    "CAROUSEL_STATUS_RESEARCHING",
    "CAROUSEL_THEMES",
    "CAROUSEL_WIDTH",
    "DEFAULT_CAROUSEL_PROMPT_VERSION",
    "DEFAULT_TEMPLATE_VERSION",
    "HD_SUBDIR_NAME",
    "IMAGE_FORMAT_JPEG",
    "IMAGE_FORMAT_JPEG_LOWER",
    "IMAGE_FORMAT_PNG",
    "IMAGE_FORMAT_WEBP",
    "IMAGE_MODEL_DEFAULT",
    "IMAGE_MODEL_GEMINI",
    "IMAGE_MODEL_OPENAI",
    "IMAGE_STYLE_CINEMATIC",
    "IMAGE_STYLE_COMIC_NEON",
    "IMAGE_STYLE_DEFAULT",
    "IMAGE_STYLE_FLAT_EDITORIAL",
    "IMAGE_STYLE_HYPERREAL",
    "IMAGE_STYLE_NEO_ANIME",
    "LANGUAGE_EN",
    "LANGUAGE_PT",
    "LIGHT_THEME_KEYS",
    "RESEARCH_SOURCE_BLOG",
    "RESEARCH_SOURCE_DOCUMENTATION",
    "RESEARCH_SOURCE_GITHUB",
    "RESEARCH_SOURCE_NEWS",
    "RESEARCH_SOURCE_REDDIT",
    "RESEARCH_SOURCE_TWITTER",
    "SHARED_IMAGES_DIR_NAME",
    "SLIDE_FILENAME_PREFIX",
    "SLIDE_IMAGE_EXTENSION",
    "SLIDE_TYPE_CLOSING",
    "SLIDE_TYPE_CONTENT",
    "SLIDE_TYPE_CTA",
    "SLIDE_TYPE_INTRO",
    "SLIDE_TYPE_SUMMARY",
    "SUPPORTED_IMAGE_COMBOS",
    "SWIPE_TEXT_EN",
    "SWIPE_TEXT_PT",
    "TEMPLATE_VERSION_V1",
    "TEMPLATE_VERSION_V2",
    "THEME_CATEGORY_KEYWORDS",
    "VALID_CAROUSEL_STATUSES",
    "VALID_IMAGE_MODELS",
    "VALID_IMAGE_STYLES",
    "VALID_RESEARCH_SOURCE_TYPES",
]
