"""Carousel theme palettes, brand palettes, and keyword mappings."""

# Theme color palettes
CAROUSEL_THEMES: dict[str, dict[str, str]] = {
    "cybersecurity": {
        "primary": "#ef4444",
        "accent": "#00d4ff",
        "background": "#0a0e17",
    },
    "ai_competition": {
        "primary": "#3b82f6",
        "accent": "#f59e0b",
        "background": "#0a0e17",
    },
    "developer_skills": {
        "primary": "#0ac5a8",
        "accent": "#8b5cf6",
        "background": "#080c12",
    },
    "source_code": {
        "primary": "#a855f7",
        "accent": "#f97316",
        "background": "#0c0a14",
    },
    "social_engineering": {
        "primary": "#f59e0b",
        "accent": "#ef4444",
        "background": "#0a0c14",
    },
}

# Brand color palettes
BRAND_PALETTES: dict[str, dict[str, str]] = {
    "anthropic": {
        "primary": "#ea580c",
        "accent": "#22d3ee",
        "background": "#0a0b12",
    },
    "google": {
        "primary": "#3b82f6",
        "accent": "#f59e0b",
        "background": "#0a0e17",
    },
    "openai": {
        "primary": "#10a37f",
        "accent": "#f59e0b",
        "background": "#0a0e17",
    },
    "meta": {
        "primary": "#8b5cf6",
        "accent": "#0ac5a8",
        "background": "#0c0a14",
    },
    "microsoft": {
        "primary": "#0078d4",
        "accent": "#f59e0b",
        "background": "#0a0e17",
    },
    "glm": {
        "primary": "#2563eb",
        "accent": "#06b6d4",
        "background": "#0a0e17",
    },
}

# Brand keywords
BRAND_KEYWORDS: dict[str, list[str]] = {
    "anthropic": [
        "anthropic",
        "claude",
        "claude code",
        "opus",
        "sonnet",
        "haiku",
        "mcp",
        "computer use",
        "dario amodei",
        "daniela amodei",
    ],
    "google": [
        "google",
        "gemma",
        "gemini",
        "deepmind",
        "alphabet",
        "bard",
        "palm",
        "tensor",
        "tpu",
        "android",
    ],
    "openai": [
        "openai",
        "chatgpt",
        "gpt",
        "gpt-4",
        "gpt-5",
        "gpt-3",
        "gpt4",
        "gpt5",
        "gpt-4o",
        "gpt-4.5",
        "gpt-5.5",
        "dall-e",
        "sora",
        "o1",
        "o3",
        "sam altman",
        "greg brockman",
    ],
    "glm": [
        "glm",
        "glm-4",
        "glm-5",
        "glm-4.5",
        "glm-5.1",
        "glm4",
        "glm5",
        "chatglm",
        "zhipu",
        "zhupai",
        "z.ai",
    ],
    "meta": [
        "meta",
        "facebook",
        "llama",
        "llama-2",
        "llama-3",
        "llama2",
        "llama3",
        "pytorch",
        "zuckerberg",
        "instagram",
        "whatsapp",
    ],
    "microsoft": [
        "microsoft",
        "azure",
        "copilot",
        "github copilot",
        "bing",
        "satya nadella",
        "windows",
        "xbox",
        "vs code",
        "visual studio",
    ],
}

# Category keywords
THEME_CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "cybersecurity": [
        "security",
        "attack",
        "vulnerability",
        "exploit",
        "breach",
        "hack",
        "zero-day",
        "zero day",
        "cve",
        "malware",
        "ransomware",
        "phishing",
        "pentest",
        "penetration",
        "backdoor",
        "trojan",
        "worm",
        "firewall",
        "cryptography",
        "encryption",
        "tls",
        "ssl",
        "oauth",
        "injection",
        "xss",
        "csrf",
        "sqli",
        "reverse shell",
        "rootkit",
        "ddos",
        "botnet",
        "apt",
        "threat",
        "incident response",
        "forensics",
        "blue team",
        "red team",
        "purple team",
        "soc",
        "siem",
        "ids",
        "ips",
    ],
    "ai_competition": [
        "ai",
        "artificial intelligence",
        "machine learning",
        "deep learning",
        "neural",
        "model",
        "llm",
        "benchmark",
        "leaderboard",
        "arena",
        "competition",
        "race",
        "rival",
        "versus",
        "vs",
        "comparison",
        "outperform",
        "surpass",
        "beat",
        "match",
        "parameter",
        "transformer",
        "attention",
        "mixture of experts",
        "moe",
        "quantization",
        "fine-tuning",
        "pre-training",
        "inference",
        "latency",
        "throughput",
        "token",
        "context window",
        "multimodal",
        "agent",
        "agentic",
        "swarm",
        "orchestration",
    ],
    "developer_skills": [
        "tutorial",
        "skill",
        "dev",
        "developer",
        "programming",
        "coding",
        "best practice",
        "pattern",
        "architecture",
        "refactoring",
        "clean code",
        "solid",
        "dry",
        "kiss",
        "design pattern",
        "microservice",
        "monolith",
        "api",
        "rest",
        "graphql",
        "grpc",
        "database",
        "sql",
        "nosql",
        "cache",
        "queue",
        "event",
        "ci/cd",
        "devops",
        "sre",
        "observability",
        "monitoring",
        "logging",
        "tracing",
        "testing",
        "tdd",
        "unit test",
        "integration test",
        "e2e",
    ],
    "source_code": [
        "leak",
        "vazou",
        "source code",
        "repository",
        "github",
        "gitlab",
        "bitbucket",
        "npm",
        "package",
        "codebase",
        "open source",
        "opensource",
        "foss",
        "license",
        "apache",
        "mit",
        "gpl",
        "commit",
        "pull request",
        "merge",
        "branch",
        "diff",
        "patch",
        "reverse engineering",
        "decompilation",
        "binary",
        "firmware",
        "sdk",
    ],
    "social_engineering": [
        "social engineering",
        "spear phishing",
        "pretexting",
        "baiting",
        "quid pro quo",
        "tailgating",
        "impersonation",
        "identity theft",
        "fraud",
        "scam",
        "deepfake",
        "voice clone",
        "manipulation",
        "psychological",
        "trust",
        "authority",
        "urgency",
        "fear",
        "curiosity",
        "greed",
    ],
}


__all__ = [
    "BRAND_KEYWORDS",
    "BRAND_PALETTES",
    "CAROUSEL_THEMES",
    "THEME_CATEGORY_KEYWORDS",
]
