"""Carousel theme palettes, brand palettes, and keyword mappings.

Single source of truth: ``PALETTE_REGISTRY`` (AE-0266). The legacy lookup dicts
and key sets below are DERIVED from it, so adding a palette is one registry row
and the views can never desync. Brand keywords sit on the brand's own row next
to its colors.
"""

from rag_backend.domain.constants.palette_types import (
    Palette,
    PaletteDescriptor,
    PaletteKind,
    PaletteMode,
)

PALETTE_REGISTRY: tuple[PaletteDescriptor, ...] = (
    PaletteDescriptor(
        key="cybersecurity",
        palette=Palette("#ef4444", "#00d4ff", "#0a0e17"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.CATEGORY,
        keywords=(
            "security",
            "attack",
            "vulnerability",
            "exploit",
            "breach",
            "hack",
            "zero-day",
            "zero day",
            "cve",
            "malware",
            "ransomware",
            "phishing",
            "pentest",
            "penetration",
            "backdoor",
            "trojan",
            "worm",
            "firewall",
            "cryptography",
            "encryption",
            "tls",
            "ssl",
            "oauth",
            "injection",
            "xss",
            "csrf",
            "sqli",
            "reverse shell",
            "rootkit",
            "ddos",
            "botnet",
            "apt",
            "threat",
            "incident response",
            "forensics",
            "blue team",
            "red team",
            "purple team",
            "soc",
            "siem",
            "ids",
            "ips",
        ),
        auto_selectable=True,
        label_en="Cybersecurity",
        label_pt="Cibersegurança",
    ),
    PaletteDescriptor(
        key="ai_competition",
        palette=Palette("#3b82f6", "#f59e0b", "#0a0e17"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.CATEGORY,
        keywords=(
            "ai",
            "artificial intelligence",
            "machine learning",
            "deep learning",
            "neural",
            "model",
            "llm",
            "benchmark",
            "leaderboard",
            "arena",
            "competition",
            "race",
            "rival",
            "versus",
            "vs",
            "comparison",
            "outperform",
            "surpass",
            "beat",
            "match",
            "parameter",
            "transformer",
            "attention",
            "mixture of experts",
            "moe",
            "quantization",
            "fine-tuning",
            "pre-training",
            "inference",
            "latency",
            "throughput",
            "token",
            "context window",
            "multimodal",
            "agent",
            "agentic",
            "swarm",
            "orchestration",
        ),
        auto_selectable=True,
        label_en="AI Competition",
        label_pt="Competição de IA",
    ),
    PaletteDescriptor(
        key="developer_skills",
        palette=Palette("#0ac5a8", "#8b5cf6", "#080c12"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.CATEGORY,
        keywords=(
            "tutorial",
            "skill",
            "dev",
            "developer",
            "programming",
            "coding",
            "best practice",
            "pattern",
            "architecture",
            "refactoring",
            "clean code",
            "solid",
            "dry",
            "kiss",
            "design pattern",
            "microservice",
            "monolith",
            "api",
            "rest",
            "graphql",
            "grpc",
            "database",
            "sql",
            "nosql",
            "cache",
            "queue",
            "event",
            "ci/cd",
            "devops",
            "sre",
            "observability",
            "monitoring",
            "logging",
            "tracing",
            "testing",
            "tdd",
            "unit test",
            "integration test",
            "e2e",
        ),
        auto_selectable=True,
        label_en="Developer Skills",
        label_pt="Habilidades de Dev",
    ),
    PaletteDescriptor(
        key="source_code",
        palette=Palette("#a855f7", "#f97316", "#0c0a14"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.CATEGORY,
        keywords=(
            "leak",
            "vazou",
            "source code",
            "repository",
            "github",
            "gitlab",
            "bitbucket",
            "npm",
            "package",
            "codebase",
            "open source",
            "opensource",
            "foss",
            "license",
            "apache",
            "mit",
            "gpl",
            "commit",
            "pull request",
            "merge",
            "branch",
            "diff",
            "patch",
            "reverse engineering",
            "decompilation",
            "binary",
            "firmware",
            "sdk",
        ),
        auto_selectable=True,
        label_en="Source Code",
        label_pt="Código Fonte",
    ),
    PaletteDescriptor(
        key="social_engineering",
        palette=Palette("#f59e0b", "#ef4444", "#0a0c14"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.CATEGORY,
        keywords=(
            "social engineering",
            "spear phishing",
            "pretexting",
            "baiting",
            "quid pro quo",
            "tailgating",
            "impersonation",
            "identity theft",
            "fraud",
            "scam",
            "deepfake",
            "voice clone",
            "manipulation",
            "psychological",
            "trust",
            "authority",
            "urgency",
            "fear",
            "curiosity",
            "greed",
        ),
        auto_selectable=True,
        label_en="Social Engineering",
        label_pt="Engenharia Social",
    ),
    PaletteDescriptor(
        key="plasma_magenta",
        palette=Palette("#ec4899", "#22d3ee", "#0a0a14"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.VARIANT,
        label_en="Plasma Magenta",
        label_pt="Plasma Magenta",
    ),
    PaletteDescriptor(
        key="acid_lime",
        palette=Palette("#a3e635", "#06b6d4", "#0b0f0a"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.VARIANT,
        label_en="Acid Lime",
        label_pt="Acid Lime",
    ),
    PaletteDescriptor(
        key="mono_indigo",
        palette=Palette("#6366f1", "#e5e7eb", "#0b0b14"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.VARIANT,
        label_en="Mono Indigo",
        label_pt="Mono Indigo",
    ),
    PaletteDescriptor(
        key="ember_crimson",
        palette=Palette("#f43f5e", "#fb923c", "#140a0c"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.VARIANT,
        label_en="Ember Crimson",
        label_pt="Ember Crimson",
    ),
    PaletteDescriptor(
        key="blueprint",
        palette=Palette("#38bdf8", "#f8fafc", "#0a192f"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.VARIANT,
        label_en="Blueprint",
        label_pt="Blueprint",
    ),
    PaletteDescriptor(
        key="risograph",
        palette=Palette("#ff5c39", "#1d4ed8", "#fbf7f0"),
        mode=PaletteMode.LIGHT,
        kind=PaletteKind.VARIANT,
        label_en="Risograph (light)",
        label_pt="Risograph (claro)",
    ),
    PaletteDescriptor(
        key="paper_editorial",
        palette=Palette("#111827", "#2563eb", "#f7f5f0"),
        mode=PaletteMode.LIGHT,
        kind=PaletteKind.VARIANT,
        label_en="Paper Editorial (light)",
        label_pt="Paper Editorial (claro)",
    ),
    PaletteDescriptor(
        key="clinical_mint",
        palette=Palette("#0f172a", "#0d9488", "#f0fdfa"),
        mode=PaletteMode.LIGHT,
        kind=PaletteKind.VARIANT,
        label_en="Clinical Mint (light)",
        label_pt="Clinical Mint (claro)",
    ),
    PaletteDescriptor(
        key="anthropic",
        palette=Palette("#ea580c", "#22d3ee", "#0a0b12"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.BRAND,
        keywords=(
            "anthropic",
            "claude",
            "claude code",
            "opus",
            "sonnet",
            "haiku",
            "mcp",
            "computer use",
            "dario amodei",
            "daniela amodei",
        ),
    ),
    PaletteDescriptor(
        key="google",
        palette=Palette("#3b82f6", "#f59e0b", "#0a0e17"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.BRAND,
        keywords=(
            "google",
            "gemma",
            "gemini",
            "deepmind",
            "alphabet",
            "bard",
            "palm",
            "tensor",
            "tpu",
            "android",
        ),
    ),
    PaletteDescriptor(
        key="openai",
        palette=Palette("#10a37f", "#f59e0b", "#0a0e17"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.BRAND,
        keywords=(
            "openai",
            "chatgpt",
            "gpt",
            "gpt-4",
            "gpt-5",
            "gpt-3",
            "gpt4",
            "gpt5",
            "gpt-4o",
            "gpt-4.5",
            "gpt-5.5",
            "dall-e",
            "sora",
            "o1",
            "o3",
            "sam altman",
            "greg brockman",
        ),
    ),
    PaletteDescriptor(
        key="meta",
        palette=Palette("#8b5cf6", "#0ac5a8", "#0c0a14"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.BRAND,
        keywords=(
            "meta",
            "facebook",
            "llama",
            "llama-2",
            "llama-3",
            "llama2",
            "llama3",
            "pytorch",
            "zuckerberg",
            "instagram",
            "whatsapp",
        ),
    ),
    PaletteDescriptor(
        key="microsoft",
        palette=Palette("#0078d4", "#f59e0b", "#0a0e17"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.BRAND,
        keywords=(
            "microsoft",
            "azure",
            "copilot",
            "github copilot",
            "bing",
            "satya nadella",
            "windows",
            "xbox",
            "vs code",
            "visual studio",
        ),
    ),
    PaletteDescriptor(
        key="glm",
        palette=Palette("#2563eb", "#06b6d4", "#0a0e17"),
        mode=PaletteMode.DARK,
        kind=PaletteKind.BRAND,
        keywords=(
            "glm",
            "glm-4",
            "glm-5",
            "glm-4.5",
            "glm-5.1",
            "glm4",
            "glm5",
            "chatglm",
            "zhipu",
            "zhupai",
            "z.ai",
        ),
    ),
)

# --- Derived views (do not hand-edit; add a PALETTE_REGISTRY row instead) ---
_BRANDS = tuple(d for d in PALETTE_REGISTRY if d.kind is PaletteKind.BRAND)
_NON_BRAND = tuple(d for d in PALETTE_REGISTRY if d.kind is not PaletteKind.BRAND)

CAROUSEL_THEMES: dict[str, dict[str, str]] = {
    d.key: d.palette.as_theme_dict() for d in _NON_BRAND
}
BRAND_PALETTES: dict[str, dict[str, str]] = {
    d.key: d.palette.as_theme_dict() for d in _BRANDS
}
BRAND_KEYWORDS: dict[str, list[str]] = {d.key: list(d.keywords) for d in _BRANDS}
THEME_CATEGORY_KEYWORDS: dict[str, list[str]] = {
    d.key: list(d.keywords) for d in PALETTE_REGISTRY if d.kind is PaletteKind.CATEGORY
}
AUTO_ROTATION_THEME_KEYS: tuple[str, ...] = tuple(
    d.key for d in PALETTE_REGISTRY if d.auto_selectable
)
LIGHT_THEME_KEYS: frozenset[str] = frozenset(
    d.key for d in PALETTE_REGISTRY if d.mode is PaletteMode.LIGHT
)

__all__ = [
    "AUTO_ROTATION_THEME_KEYS",
    "BRAND_KEYWORDS",
    "BRAND_PALETTES",
    "CAROUSEL_THEMES",
    "LIGHT_THEME_KEYS",
    "PALETTE_REGISTRY",
    "THEME_CATEGORY_KEYWORDS",
]
