"""Keyword maps for brand and category theme auto-detection.

Split out of ``carousel_themes`` so the palette catalog stays focused and
both files stay under the 400-line ceiling. ``carousel.py`` re-exports
these so existing ``domain.constants`` imports are unaffected.
"""

# Brand keywords
BRAND_KEYWORDS: dict[str, list[str]] = {
    "anthropic": [
        "anthropic",
        "claude",
        "claude code",
        "opus",
        "sonnet",
        "haiku",
        "mcp",
        "computer use",
        "dario amodei",
        "daniela amodei",
    ],
    "google": [
        "google",
        "gemma",
        "gemini",
        "deepmind",
        "alphabet",
        "bard",
        "palm",
        "tensor",
        "tpu",
        "android",
    ],
    "openai": [
        "openai",
        "chatgpt",
        "gpt",
        "gpt-4",
        "gpt-5",
        "gpt-3",
        "gpt4",
        "gpt5",
        "gpt-4o",
        "gpt-4.5",
        "gpt-5.5",
        "dall-e",
        "sora",
        "o1",
        "o3",
        "sam altman",
        "greg brockman",
    ],
    "glm": [
        "glm",
        "glm-4",
        "glm-5",
        "glm-4.5",
        "glm-5.1",
        "glm4",
        "glm5",
        "chatglm",
        "zhipu",
        "zhupai",
        "z.ai",
    ],
    "meta": [
        "meta",
        "facebook",
        "llama",
        "llama-2",
        "llama-3",
        "llama2",
        "llama3",
        "pytorch",
        "zuckerberg",
        "instagram",
        "whatsapp",
    ],
    "microsoft": [
        "microsoft",
        "azure",
        "copilot",
        "github copilot",
        "bing",
        "satya nadella",
        "windows",
        "xbox",
        "vs code",
        "visual studio",
    ],
}

# Category keywords
THEME_CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "cybersecurity": [
        "security",
        "attack",
        "vulnerability",
        "exploit",
        "breach",
        "hack",
        "zero-day",
        "zero day",
        "cve",
        "malware",
        "ransomware",
        "phishing",
        "pentest",
        "penetration",
        "backdoor",
        "trojan",
        "worm",
        "firewall",
        "cryptography",
        "encryption",
        "tls",
        "ssl",
        "oauth",
        "injection",
        "xss",
        "csrf",
        "sqli",
        "reverse shell",
        "rootkit",
        "ddos",
        "botnet",
        "apt",
        "threat",
        "incident response",
        "forensics",
        "blue team",
        "red team",
        "purple team",
        "soc",
        "siem",
        "ids",
        "ips",
    ],
    "ai_competition": [
        "ai",
        "artificial intelligence",
        "machine learning",
        "deep learning",
        "neural",
        "model",
        "llm",
        "benchmark",
        "leaderboard",
        "arena",
        "competition",
        "race",
        "rival",
        "versus",
        "vs",
        "comparison",
        "outperform",
        "surpass",
        "beat",
        "match",
        "parameter",
        "transformer",
        "attention",
        "mixture of experts",
        "moe",
        "quantization",
        "fine-tuning",
        "pre-training",
        "inference",
        "latency",
        "throughput",
        "token",
        "context window",
        "multimodal",
        "agent",
        "agentic",
        "swarm",
        "orchestration",
    ],
    "developer_skills": [
        "tutorial",
        "skill",
        "dev",
        "developer",
        "programming",
        "coding",
        "best practice",
        "pattern",
        "architecture",
        "refactoring",
        "clean code",
        "solid",
        "dry",
        "kiss",
        "design pattern",
        "microservice",
        "monolith",
        "api",
        "rest",
        "graphql",
        "grpc",
        "database",
        "sql",
        "nosql",
        "cache",
        "queue",
        "event",
        "ci/cd",
        "devops",
        "sre",
        "observability",
        "monitoring",
        "logging",
        "tracing",
        "testing",
        "tdd",
        "unit test",
        "integration test",
        "e2e",
    ],
    "source_code": [
        "leak",
        "vazou",
        "source code",
        "repository",
        "github",
        "gitlab",
        "bitbucket",
        "npm",
        "package",
        "codebase",
        "open source",
        "opensource",
        "foss",
        "license",
        "apache",
        "mit",
        "gpl",
        "commit",
        "pull request",
        "merge",
        "branch",
        "diff",
        "patch",
        "reverse engineering",
        "decompilation",
        "binary",
        "firmware",
        "sdk",
    ],
    "social_engineering": [
        "social engineering",
        "spear phishing",
        "pretexting",
        "baiting",
        "quid pro quo",
        "tailgating",
        "impersonation",
        "identity theft",
        "fraud",
        "scam",
        "deepfake",
        "voice clone",
        "manipulation",
        "psychological",
        "trust",
        "authority",
        "urgency",
        "fear",
        "curiosity",
        "greed",
    ],
}


__all__ = [
    "BRAND_KEYWORDS",
    "THEME_CATEGORY_KEYWORDS",
]
