"""Conversation metadata and filtering constants."""

CONVERSATION_METADATA_PROJECT_ID = "project_id"
CONVERSATION_METADATA_AGENT_ORIGIN = "agent_origin"

AGENT_ORIGIN_ALTER_EGO = "alter_ego"
AGENT_ORIGIN_CAROUSEL = "carousel"

CONVERSATION_ORIGIN_FILTER_ALTER_EGO = "alter_ego"
CONVERSATION_ORIGIN_FILTER_CAROUSEL = "carousel"

ERR_CAROUSEL_CONVERSATION_REQUIRES_AUTH = (
    "Carousel conversations require an authenticated owner"
)
ERR_CAROUSEL_CONVERSATION_PROJECT_DENIED = (
    "You do not have access to bind this carousel project"
)
ERR_ANONYMOUS_CAROUSEL_CONVERSATION = (
    "Anonymous conversations cannot use carousel publish chat"
)
ERR_CONVERSATION_OWNERSHIP_DENIED = "You do not own this conversation"

__all__ = [
    "AGENT_ORIGIN_ALTER_EGO",
    "AGENT_ORIGIN_CAROUSEL",
    "CONVERSATION_METADATA_AGENT_ORIGIN",
    "CONVERSATION_METADATA_PROJECT_ID",
    "CONVERSATION_ORIGIN_FILTER_ALTER_EGO",
    "CONVERSATION_ORIGIN_FILTER_CAROUSEL",
    "ERR_ANONYMOUS_CAROUSEL_CONVERSATION",
    "ERR_CAROUSEL_CONVERSATION_PROJECT_DENIED",
    "ERR_CAROUSEL_CONVERSATION_REQUIRES_AUTH",
    "ERR_CONVERSATION_OWNERSHIP_DENIED",
]
