"""Constants for the notification system (NOTIF-001, NOTIF-002)."""

NOTIFICATION_TYPE_REVIEW_REQUEST = "review_request"
NOTIFICATION_TYPE_REVIEW_COMPLETED = "review_completed"
NOTIFICATION_TYPE_PHASE_APPROVED = "phase_approved"
NOTIFICATION_TYPE_PHASE_REJECTED = "phase_rejected"
NOTIFICATION_TYPE_DEADLINE_REMINDER = "deadline_reminder"
NOTIFICATION_TYPE_SCHEDULED_PUBLISHED = "scheduled_published"
NOTIFICATION_TYPE_ASSIGNMENT = "review_assignment"

NOTIFICATION_CHANNEL_IN_APP = "in_app"
NOTIFICATION_CHANNEL_EMAIL = "email"

NOTIFICATION_STATUS_UNREAD = "unread"
NOTIFICATION_STATUS_READ = "read"
NOTIFICATION_STATUS_DISMISSED = "dismissed"

DEFAULT_REVIEW_DEADLINE_HOURS = 24
DEADLINE_REMINDER_INTERVAL_SECONDS = 3600

EMAIL_SUBJECT_REVIEW_REQUEST = "Review requested: {title}"
EMAIL_SUBJECT_DEADLINE_REMINDER = "Reminder: pending review for {title}"
EMAIL_SUBJECT_SCHEDULED_PUBLISHED = "Your post is now live: {title}"

ERR_NOTIFICATION_NOT_FOUND = "notification_not_found"

__all__ = [
    "DEADLINE_REMINDER_INTERVAL_SECONDS",
    "DEFAULT_REVIEW_DEADLINE_HOURS",
    "EMAIL_SUBJECT_DEADLINE_REMINDER",
    "EMAIL_SUBJECT_REVIEW_REQUEST",
    "EMAIL_SUBJECT_SCHEDULED_PUBLISHED",
    "ERR_NOTIFICATION_NOT_FOUND",
    "NOTIFICATION_CHANNEL_EMAIL",
    "NOTIFICATION_CHANNEL_IN_APP",
    "NOTIFICATION_STATUS_DISMISSED",
    "NOTIFICATION_STATUS_READ",
    "NOTIFICATION_STATUS_UNREAD",
    "NOTIFICATION_TYPE_ASSIGNMENT",
    "NOTIFICATION_TYPE_DEADLINE_REMINDER",
    "NOTIFICATION_TYPE_PHASE_APPROVED",
    "NOTIFICATION_TYPE_PHASE_REJECTED",
    "NOTIFICATION_TYPE_REVIEW_COMPLETED",
    "NOTIFICATION_TYPE_REVIEW_REQUEST",
    "NOTIFICATION_TYPE_SCHEDULED_PUBLISHED",
]
