"""Constants for plagiarism detection (QUAL-001)."""

PLAGIARISM_THRESHOLD_PASS = 85.0
PLAGIARISM_THRESHOLD_WARN = 70.0
PLAGIARISM_NGRAM_SIZE = 5
PLAGIARISM_MIN_OVERLAP_RATIO = 0.15
PLAGIARISM_MIN_TEXTS = 2

SEVERITY_PASS = "pass"
SEVERITY_WARN = "warn"
SEVERITY_FAIL = "fail"

FIELD_OVERALL_SCORE = "overall_score"
FIELD_MATCHES = "matches"
FIELD_PASSED = "passed"
FIELD_SEVERITY = "severity"

__all__ = [
    "FIELD_MATCHES",
    "FIELD_OVERALL_SCORE",
    "FIELD_PASSED",
    "FIELD_SEVERITY",
    "PLAGIARISM_MIN_OVERLAP_RATIO",
    "PLAGIARISM_MIN_TEXTS",
    "PLAGIARISM_NGRAM_SIZE",
    "PLAGIARISM_THRESHOLD_PASS",
    "PLAGIARISM_THRESHOLD_WARN",
    "SEVERITY_FAIL",
    "SEVERITY_PASS",
    "SEVERITY_WARN",
]
