"""Constants for Playwright export geometry and decode preflight."""

VIOLATION_FONT_UNAVAILABLE = "font_unavailable"
VIOLATION_FONT_READY_TIMEOUT = "font_ready_timeout"
VIOLATION_IMAGE_DECODE_FAILED = "image_decode_failed"
VIOLATION_IMAGE_DECODE_TIMEOUT = "image_decode_timeout"
VIOLATION_LAYOUT_COPY_ABOVE_BOUNDARY = "layout_copy_above_boundary"
VIOLATION_LAYOUT_COPY_OVERFLOW = "layout_copy_overflow"
VIOLATION_LAYOUT_COPY_DESCENDANT_OVERFLOW = "layout_copy_descendant_overflow"
VIOLATION_LAYOUT_FOOTER_OUT_OF_BOUNDS = "layout_footer_out_of_bounds"
VIOLATION_LAYOUT_MISSING_REGION = "layout_missing_region"
VIOLATION_LAYOUT_NEAR_LIMIT = "layout_near_limit"
VIOLATION_LAYOUT_OVERFLOW_SCROLL = "layout_overflow_scroll"
VIOLATION_LAYOUT_PRESENTATION_BELOW_FOOTER = "layout_presentation_below_footer"
VIOLATION_CTA_CARD_OUT_OF_BOUNDS = "cta_card_out_of_bounds"
VIOLATION_CTA_WEBSITE_COUNT = "cta_website_count_invalid"

PREFLIGHT_SCALE_STANDARD = "standard"
PREFLIGHT_SCALE_HD = "hd"

FONT_CHECK_HEADING_SIZE_PX = 16
FONT_CHECK_BODY_SIZE_PX = 14
FONT_CHECK_BADGE_SIZE_PX = 12

FONT_READY_TIMEOUT_MS = 15_000
IMAGE_DECODE_TIMEOUT_PER_MS = 20_000
IMAGE_DECODE_TIMEOUT_TOTAL_MS = 120_000

ERR_EXPORT_PREFLIGHT_FAILED = "export_preflight_failed"
ERR_SCREENSHOT_DIMENSION_MISMATCH = "screenshot_dimension_mismatch"

SELECTOR_KEY_SLIDE_ROOT = "slide_root"
SELECTOR_KEY_ARTWORK = "artwork"
SELECTOR_KEY_PRESENTATION = "presentation"
SELECTOR_KEY_COPY = "copy"
SELECTOR_KEY_FOOTER = "footer"
SELECTOR_KEY_CTA_CARD = "cta_card"
SELECTOR_KEY_CTA_AVATAR = "cta_avatar"

__all__ = [
    "ERR_EXPORT_PREFLIGHT_FAILED",
    "ERR_SCREENSHOT_DIMENSION_MISMATCH",
    "FONT_CHECK_BADGE_SIZE_PX",
    "FONT_CHECK_BODY_SIZE_PX",
    "FONT_CHECK_HEADING_SIZE_PX",
    "FONT_READY_TIMEOUT_MS",
    "IMAGE_DECODE_TIMEOUT_PER_MS",
    "IMAGE_DECODE_TIMEOUT_TOTAL_MS",
    "PREFLIGHT_SCALE_HD",
    "PREFLIGHT_SCALE_STANDARD",
    "SELECTOR_KEY_ARTWORK",
    "SELECTOR_KEY_COPY",
    "SELECTOR_KEY_CTA_AVATAR",
    "SELECTOR_KEY_CTA_CARD",
    "SELECTOR_KEY_FOOTER",
    "SELECTOR_KEY_PRESENTATION",
    "SELECTOR_KEY_SLIDE_ROOT",
    "VIOLATION_CTA_CARD_OUT_OF_BOUNDS",
    "VIOLATION_CTA_WEBSITE_COUNT",
    "VIOLATION_FONT_READY_TIMEOUT",
    "VIOLATION_FONT_UNAVAILABLE",
    "VIOLATION_IMAGE_DECODE_FAILED",
    "VIOLATION_IMAGE_DECODE_TIMEOUT",
    "VIOLATION_LAYOUT_COPY_ABOVE_BOUNDARY",
    "VIOLATION_LAYOUT_COPY_DESCENDANT_OVERFLOW",
    "VIOLATION_LAYOUT_COPY_OVERFLOW",
    "VIOLATION_LAYOUT_FOOTER_OUT_OF_BOUNDS",
    "VIOLATION_LAYOUT_MISSING_REGION",
    "VIOLATION_LAYOUT_NEAR_LIMIT",
    "VIOLATION_LAYOUT_OVERFLOW_SCROLL",
    "VIOLATION_LAYOUT_PRESENTATION_BELOW_FOOTER",
]
