"""Presentation policy version identifiers and loader error messages."""

PRESENTATION_POLICY_VERSION_HERO_LOWER_THIRD_V1 = "hero_lower_third_v1"
DEFAULT_PRESENTATION_POLICY_VERSION = PRESENTATION_POLICY_VERSION_HERO_LOWER_THIRD_V1

ERR_PRESENTATION_POLICY_NOT_FOUND = "presentation_policy_not_found"
ERR_PRESENTATION_POLICY_INVALID = "presentation_policy_invalid"
ERR_PRESENTATION_POLICY_VERSION_UNKNOWN = "presentation_policy_version_unknown"

SUPPORTED_PRESENTATION_POLICY_VERSIONS: frozenset[str] = frozenset({
    PRESENTATION_POLICY_VERSION_HERO_LOWER_THIRD_V1
})

CONTRACTS_SUBDIR = "contracts"
POLICY_FILE_SUFFIX = ".yaml"

__all__ = [
    "CONTRACTS_SUBDIR",
    "DEFAULT_PRESENTATION_POLICY_VERSION",
    "ERR_PRESENTATION_POLICY_INVALID",
    "ERR_PRESENTATION_POLICY_NOT_FOUND",
    "ERR_PRESENTATION_POLICY_VERSION_UNKNOWN",
    "POLICY_FILE_SUFFIX",
    "PRESENTATION_POLICY_VERSION_HERO_LOWER_THIRD_V1",
    "SUPPORTED_PRESENTATION_POLICY_VERSIONS",
]
