"""Retry-related constants for external API calls."""

DEFAULT_MAX_ATTEMPTS = 3
DEFAULT_MIN_WAIT_SECONDS = 1.0
DEFAULT_MAX_WAIT_SECONDS = 30.0
GEMINI_MAX_ATTEMPTS = 3
META_MAX_ATTEMPTS = 3
PINECONE_MAX_ATTEMPTS = 3
LANGGRAPH_MAX_ATTEMPTS = 3
META_POLL_MAX_ATTEMPTS = 30
META_POLL_INTERVAL_SECONDS = 2.0
