"""Constants for SEO analysis (QUAL-003)."""

SEO_TITLE_MIN_LENGTH = 30
SEO_TITLE_MAX_LENGTH = 60
SEO_TITLE_IDEAL_MIN = 50
SEO_TITLE_IDEAL_MAX = 60

SEO_DESCRIPTION_MIN_LENGTH = 70
SEO_DESCRIPTION_MAX_LENGTH = 160
SEO_DESCRIPTION_IDEAL_MIN = 120
SEO_DESCRIPTION_IDEAL_MAX = 160

SEO_SLUG_MAX_LENGTH = 75
SEO_KEYWORD_MIN_COUNT = 1
SEO_KEYWORD_MAX_COUNT = 10

SEO_SCORE_PASS = 70
SEO_SCORE_WARN = 50

ISSUE_TITLE_TOO_SHORT = "title_too_short"
ISSUE_TITLE_TOO_LONG = "title_too_long"
ISSUE_DESCRIPTION_TOO_SHORT = "description_too_short"
ISSUE_DESCRIPTION_TOO_LONG = "description_too_long"
ISSUE_MISSING_META_TITLE = "missing_meta_title"
ISSUE_MISSING_META_DESCRIPTION = "missing_meta_description"
ISSUE_SLUG_TOO_LONG = "slug_too_long"
ISSUE_NO_KEYWORDS = "no_keywords"
ISSUE_NO_EXCERPT = "no_excerpt"

__all__ = [
    "ISSUE_DESCRIPTION_TOO_LONG",
    "ISSUE_DESCRIPTION_TOO_SHORT",
    "ISSUE_MISSING_META_DESCRIPTION",
    "ISSUE_MISSING_META_TITLE",
    "ISSUE_NO_EXCERPT",
    "ISSUE_NO_KEYWORDS",
    "ISSUE_SLUG_TOO_LONG",
    "ISSUE_TITLE_TOO_LONG",
    "ISSUE_TITLE_TOO_SHORT",
    "SEO_DESCRIPTION_IDEAL_MAX",
    "SEO_DESCRIPTION_IDEAL_MIN",
    "SEO_DESCRIPTION_MAX_LENGTH",
    "SEO_DESCRIPTION_MIN_LENGTH",
    "SEO_KEYWORD_MAX_COUNT",
    "SEO_KEYWORD_MIN_COUNT",
    "SEO_SCORE_PASS",
    "SEO_SCORE_WARN",
    "SEO_SLUG_MAX_LENGTH",
    "SEO_TITLE_IDEAL_MAX",
    "SEO_TITLE_IDEAL_MIN",
    "SEO_TITLE_MAX_LENGTH",
    "SEO_TITLE_MIN_LENGTH",
]
