"""Validation limits for Phase 3 workflow APIs."""

MAX_REJECT_REASON_LENGTH = 2000
MAX_LOCK_TTL_SECONDS = 3600
MIN_LOCK_TTL_SECONDS = 30
MAX_CALENDAR_RANGE_DAYS = 366
MAX_REVIEW_DEADLINE_HOURS = 720
MIN_REVIEW_DEADLINE_HOURS = 1
MIN_SCHEDULE_LEAD_SECONDS = 60
MAX_NOTIFICATION_TITLE_LENGTH = 255

ERR_BLOG_INVALID_STATUS = "blog_post_invalid_status"
ERR_NOT_ASSIGNED_REVIEWER = "not_assigned_reviewer"
ERR_VERSION_HEADER_REQUIRED = "if_match_required"
ERR_REVIEWER_INVALID = "reviewer_invalid"
ERR_REVIEWER_REQUIRED = "reviewer_required"
ERR_SELF_REVIEW = "self_review_not_allowed"
ERR_SCHEDULE_IN_PAST = "schedule_in_past"
ERR_CALENDAR_RANGE_TOO_LARGE = "calendar_range_too_large"
ERR_CALENDAR_RANGE_INVALID = "calendar_range_invalid"
ERR_INVALID_CONTENT_TYPE = "invalid_content_type"
ERR_REVIEWER_ASSIGNMENT_UNSUPPORTED = "reviewer_assignment_unsupported"
ERR_WORKFLOW_FIELD_IMMUTABLE = "workflow_field_immutable"

WORKFLOW_IMMUTABLE_UPDATE_FIELDS = (
    "status",
    "submitted_for_review_at",
    "approved_at",
    "published_at",
    "scheduled_publish_at",
)

WORKFLOW_REJECT_COMMENT_PREFIX = "Rejected: {reason}"
NOTIFICATION_TITLE_CHANGES_REQUESTED = "Changes requested: {title}"

CONTENT_TYPE_BLOG_POST = "blog_post"
CONTENT_TYPE_CAROUSEL = "carousel"

NOTIFICATION_BODY_REVIEW_REQUEST = "A {content_type} is waiting for your review."
NOTIFICATION_BODY_DEADLINE_REMINDER = "This review is past its deadline."
NOTIFICATION_BODY_SCHEDULED_PUBLISHED = "Your scheduled blog post has been published."

METADATA_KEY_ORIGINAL_NOTIFICATION_ID = "original_notification_id"
METADATA_KEY_REMINDER_SENT = "reminder_sent"

__all__ = [
    "CONTENT_TYPE_BLOG_POST",
    "CONTENT_TYPE_CAROUSEL",
    "ERR_BLOG_INVALID_STATUS",
    "ERR_CALENDAR_RANGE_INVALID",
    "ERR_CALENDAR_RANGE_TOO_LARGE",
    "ERR_INVALID_CONTENT_TYPE",
    "ERR_NOT_ASSIGNED_REVIEWER",
    "ERR_REVIEWER_ASSIGNMENT_UNSUPPORTED",
    "ERR_REVIEWER_INVALID",
    "ERR_REVIEWER_REQUIRED",
    "ERR_SCHEDULE_IN_PAST",
    "ERR_SELF_REVIEW",
    "ERR_VERSION_HEADER_REQUIRED",
    "ERR_WORKFLOW_FIELD_IMMUTABLE",
    "MAX_CALENDAR_RANGE_DAYS",
    "MAX_LOCK_TTL_SECONDS",
    "MAX_NOTIFICATION_TITLE_LENGTH",
    "MAX_REJECT_REASON_LENGTH",
    "MAX_REVIEW_DEADLINE_HOURS",
    "METADATA_KEY_ORIGINAL_NOTIFICATION_ID",
    "METADATA_KEY_REMINDER_SENT",
    "MIN_LOCK_TTL_SECONDS",
    "MIN_REVIEW_DEADLINE_HOURS",
    "MIN_SCHEDULE_LEAD_SECONDS",
    "NOTIFICATION_BODY_DEADLINE_REMINDER",
    "NOTIFICATION_BODY_REVIEW_REQUEST",
    "NOTIFICATION_BODY_SCHEDULED_PUBLISHED",
    "NOTIFICATION_TITLE_CHANGES_REQUESTED",
    "WORKFLOW_IMMUTABLE_UPDATE_FIELDS",
    "WORKFLOW_REJECT_COMMENT_PREFIX",
]
