"""Constants for workflow event-driven architecture (ADR-004)."""

STREAM_CONTENT_EVENTS = "content.events"
CONSUMER_GROUP_WORKFLOW = "workflow_engine"
CONSUMER_GROUP_NOTIFICATIONS = "notification_service"

EVENT_SOURCE_WORKFLOW_ENGINE = "workflow_engine"
EVENT_SOURCE_BLOG_WORKFLOW = "blog_workflow"
EVENT_SOURCE_SCHEDULER = "scheduler"

EVENT_TYPE_PROJECT_PHASE_CHANGED = "content.project.phase_changed"
EVENT_TYPE_PROJECT_REVIEW_REQUESTED = "content.project.review.requested"
EVENT_TYPE_PROJECT_REVIEW_COMPLETED = "content.project.review.completed"
EVENT_TYPE_BLOGPOST_STATUS_CHANGED = "content.blogpost.status.changed"
EVENT_TYPE_BLOGPOST_SCHEDULED = "content.blogpost.scheduled"
EVENT_TYPE_BLOGPOST_PUBLISHED = "content.blogpost.published"
EVENT_TYPE_BLOGPOST_CREATED = "content.blogpost.created"
EVENT_TYPE_BLOGPOST_UPDATED = "content.blogpost.updated"
EVENT_TYPE_BLOGPOST_DELETED = "content.blogpost.deleted"
EVENT_TYPE_BLOGPOST_COMMENT_ADDED = "content.blogpost.comment.added"
EVENT_TYPE_BLOGPOST_VERSION_RESTORED = "content.blogpost.version.restored"
EVENT_TYPE_BLOGPOST_AI_ACTION = "content.blogpost.ai.action"
EVENT_TYPE_NOTIFICATION_CREATED = "content.notification.created"

EVENT_SOURCE_EDITORIAL = "editorial"

AGGREGATE_TYPE_PROJECT = "project"
AGGREGATE_TYPE_BLOG_POST = "blog_post"

EVENT_FIELD_EVENT_ID = "event_id"
EVENT_FIELD_EVENT_TYPE = "event_type"
EVENT_FIELD_AGGREGATE_ID = "aggregate_id"
EVENT_FIELD_AGGREGATE_TYPE = "aggregate_type"
EVENT_FIELD_TIMESTAMP = "timestamp"
EVENT_FIELD_VERSION = "version"
EVENT_FIELD_PAYLOAD = "payload"
EVENT_FIELD_METADATA = "metadata"

# Session-info key holding events queued for post-commit publish (AE-0074)
SESSION_INFO_PENDING_EVENTS = "pending_workflow_events"

__all__ = [
    "AGGREGATE_TYPE_BLOG_POST",
    "AGGREGATE_TYPE_PROJECT",
    "CONSUMER_GROUP_NOTIFICATIONS",
    "CONSUMER_GROUP_WORKFLOW",
    "EVENT_FIELD_AGGREGATE_ID",
    "EVENT_FIELD_AGGREGATE_TYPE",
    "EVENT_FIELD_EVENT_ID",
    "EVENT_FIELD_EVENT_TYPE",
    "EVENT_FIELD_METADATA",
    "EVENT_FIELD_PAYLOAD",
    "EVENT_FIELD_TIMESTAMP",
    "EVENT_FIELD_VERSION",
    "EVENT_SOURCE_BLOG_WORKFLOW",
    "EVENT_SOURCE_EDITORIAL",
    "EVENT_SOURCE_SCHEDULER",
    "EVENT_SOURCE_WORKFLOW_ENGINE",
    "EVENT_TYPE_BLOGPOST_AI_ACTION",
    "EVENT_TYPE_BLOGPOST_COMMENT_ADDED",
    "EVENT_TYPE_BLOGPOST_CREATED",
    "EVENT_TYPE_BLOGPOST_DELETED",
    "EVENT_TYPE_BLOGPOST_PUBLISHED",
    "EVENT_TYPE_BLOGPOST_SCHEDULED",
    "EVENT_TYPE_BLOGPOST_STATUS_CHANGED",
    "EVENT_TYPE_BLOGPOST_UPDATED",
    "EVENT_TYPE_BLOGPOST_VERSION_RESTORED",
    "EVENT_TYPE_NOTIFICATION_CREATED",
    "EVENT_TYPE_PROJECT_PHASE_CHANGED",
    "EVENT_TYPE_PROJECT_REVIEW_COMPLETED",
    "EVENT_TYPE_PROJECT_REVIEW_REQUESTED",
    "SESSION_INFO_PENDING_EVENTS",
    "STREAM_CONTENT_EVENTS",
]
