"""Constants for workflow failure alerting (MON-002)."""

ALERT_TYPE_CAROUSEL_FAILED = "carousel_failed"
ALERT_TYPE_WORKFLOW_REJECTED = "workflow_rejected"
ALERT_TYPE_STUCK_WORKFLOW = "stuck_workflow"
ALERT_TYPE_HIGH_FAILURE_RATE = "high_failure_rate"

ALERT_LOG_EVENT = "workflow_failure_alert"
ALERT_STUCK_WORKFLOW_HOURS = 48
ALERT_FAILURE_WINDOW_HOURS = 1
ALERT_FAILURE_RATE_THRESHOLD = 0.10
ALERT_REASON_TRUNCATE_LENGTH = 200
ALERT_UNKNOWN_ERROR = "unknown error"

NOTIFICATION_TYPE_WORKFLOW_FAILURE = "workflow_failure"
NOTIFICATION_TITLE_WORKFLOW_FAILURE = "Workflow failure detected"
NOTIFICATION_BODY_CAROUSEL_FAILED = "Carousel project {project_id} failed: {reason}"
NOTIFICATION_BODY_STUCK_WORKFLOW = "Workflow stuck on project {project_id} for {hours}h"
NOTIFICATION_BODY_HIGH_FAILURE_RATE = (
    "Workflow failure rate {rate:.0%} exceeds threshold in the last hour"
)

__all__ = [
    "ALERT_FAILURE_RATE_THRESHOLD",
    "ALERT_FAILURE_WINDOW_HOURS",
    "ALERT_LOG_EVENT",
    "ALERT_REASON_TRUNCATE_LENGTH",
    "ALERT_STUCK_WORKFLOW_HOURS",
    "ALERT_TYPE_CAROUSEL_FAILED",
    "ALERT_TYPE_HIGH_FAILURE_RATE",
    "ALERT_TYPE_STUCK_WORKFLOW",
    "ALERT_TYPE_WORKFLOW_REJECTED",
    "ALERT_UNKNOWN_ERROR",
    "NOTIFICATION_BODY_CAROUSEL_FAILED",
    "NOTIFICATION_BODY_HIGH_FAILURE_RATE",
    "NOTIFICATION_BODY_STUCK_WORKFLOW",
    "NOTIFICATION_TITLE_WORKFLOW_FAILURE",
    "NOTIFICATION_TYPE_WORKFLOW_FAILURE",
]
