"""initial baseline schema

Revision ID: 63eaefa67b8c
Revises:
Create Date: 2026-06-14 20:41:27.392429

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "63eaefa67b8c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_locks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("content_id", sa.String(length=36), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("user_name", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_content_locks_content",
        "content_locks",
        ["content_type", "content_id"],
        unique=True,
    )
    op.create_index(
        "idx_content_locks_expires", "content_locks", ["expires_at"], unique=False
    )
    op.create_table(
        "content_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("content_id", sa.String(length=36), nullable=False),
        sa.Column("content_type", sa.String(length=30), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("change_summary", sa.String(length=500), nullable=True),
        sa.Column("author_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_content_versions_content_id",
        "content_versions",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        "idx_content_versions_type", "content_versions", ["content_type"], unique=False
    )
    op.create_index(
        "idx_content_versions_version",
        "content_versions",
        ["content_type", "version_number"],
        unique=True,
    )
    op.create_table(
        "editorial_comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("content_id", sa.String(length=36), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("position", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("ai_suggestion", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_editorial_comments_content_id",
        "editorial_comments",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        "idx_editorial_comments_status", "editorial_comments", ["status"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("notification_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("content_id", sa.String(length=36), nullable=True),
        sa.Column("content_type", sa.String(length=50), nullable=True),
        sa.Column("metadata", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("email_sent", sa.Boolean(), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_notifications_content",
        "notifications",
        ["content_type", "content_id"],
        unique=False,
    )
    op.create_index(
        "idx_notifications_deadline", "notifications", ["deadline_at"], unique=False
    )
    op.create_index(
        "idx_notifications_user_status",
        "notifications",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "persona_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tone_attributes", sa.JSON(), nullable=False),
        sa.Column("writing_samples", sa.JSON(), nullable=False),
        sa.Column("forbidden_phrases", sa.JSON(), nullable=False),
        sa.Column("preferred_phrases", sa.JSON(), nullable=False),
        sa.Column("sentence_structure_preferences", sa.Text(), nullable=True),
        sa.Column("paragraph_style", sa.Text(), nullable=True),
        sa.Column("opinion_expression", sa.Text(), nullable=True),
        sa.Column("expertise_areas", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_persona_profiles_name", "persona_profiles", ["name"], unique=False
    )
    op.create_index(
        "idx_persona_profiles_version", "persona_profiles", ["version"], unique=False
    )
    op.create_table(
        "quality_rubrics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("criteria", sa.JSON(), nullable=False),
        sa.Column("applicable_content_types", sa.JSON(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_quality_rubrics_is_default",
        "quality_rubrics",
        ["is_default"],
        unique=False,
    )
    op.create_index(
        "idx_quality_rubrics_name", "quality_rubrics", ["name"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("idx_users_email", "users", ["email"], unique=False)
    op.create_index("idx_users_role", "users", ["role"], unique=False)
    op.create_table(
        "workflow_audit_log",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.String(length=36), nullable=False),
        sa.Column("aggregate_type", sa.String(length=50), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("metadata", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index(
        "idx_audit_aggregate",
        "workflow_audit_log",
        ["aggregate_type", "aggregate_id"],
        unique=False,
    )
    op.create_index(
        "idx_audit_created_at", "workflow_audit_log", ["created_at"], unique=False
    )
    op.create_index(
        "idx_audit_event_type", "workflow_audit_log", ["event_type"], unique=False
    )
    op.create_table(
        "carousel_creator_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("relative_path", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id", "content_sha256", name="uq_carousel_creator_assets_owner_sha256"
        ),
    )
    op.create_index(
        "idx_carousel_creator_assets_owner",
        "carousel_creator_assets",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_conversations_owner_id", "conversations", ["owner_id"], unique=False
    )
    op.create_index(
        "idx_conversations_updated_at", "conversations", ["updated_at"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_documents_created_at", "documents", ["created_at"], unique=False
    )
    op.create_index("idx_documents_owner_id", "documents", ["owner_id"], unique=False)
    op.create_index("idx_documents_status", "documents", ["status"], unique=False)
    op.create_index(
        "idx_documents_updated_at", "documents", ["updated_at"], unique=False
    )
    op.create_table(
        "persona_corrections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("corrected_text", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("correction_type", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["persona_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_persona_corrections_created_at",
        "persona_corrections",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_persona_corrections_persona_id",
        "persona_corrections",
        ["persona_id"],
        unique=False,
    )
    op.create_table(
        "rubric_evaluation_scores",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rubric_id", sa.String(length=36), nullable=False),
        sa.Column("content_id", sa.String(length=36), nullable=False),
        sa.Column("content_type", sa.String(length=30), nullable=False),
        sa.Column(
            "evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("scores", sa.JSON(), nullable=False),
        sa.Column("overall_score", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("feedback", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rubric_id"],
            ["quality_rubrics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_rubric_scores_content_id",
        "rubric_evaluation_scores",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        "idx_rubric_scores_content_type",
        "rubric_evaluation_scores",
        ["content_type"],
        unique=False,
    )
    op.create_index(
        "idx_rubric_scores_rubric_id",
        "rubric_evaluation_scores",
        ["rubric_id"],
        unique=False,
    )
    op.create_table(
        "carousel_projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("topic", sa.String(length=500), nullable=False),
        sa.Column("audience", sa.String(length=500), nullable=False),
        sa.Column("niche", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("subtitle", sa.Text(), nullable=True),
        sa.Column("title_en", sa.String(length=500), nullable=True),
        sa.Column("subtitle_en", sa.Text(), nullable=True),
        sa.Column("slides_config", sa.String(length=200), nullable=False),
        sa.Column("aspect_ratio", sa.String(length=20), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("generate_images", sa.Integer(), nullable=False),
        sa.Column(
            "image_model", sa.String(length=30), server_default="gemini", nullable=False
        ),
        sa.Column(
            "image_style",
            sa.String(length=30),
            server_default="comic_neon",
            nullable=False,
        ),
        sa.Column("theme", sa.String(length=30), nullable=False),
        sa.Column("primary_color", sa.String(length=20), nullable=True),
        sa.Column("accent_color", sa.String(length=20), nullable=True),
        sa.Column("background_color", sa.String(length=20), nullable=True),
        sa.Column("blog_markdown", sa.Text(), nullable=True),
        sa.Column("blog_translations", sa.JSON(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("caption_en", sa.Text(), nullable=True),
        sa.Column("linkedin_post_pt", sa.Text(), nullable=True),
        sa.Column("linkedin_post_en", sa.Text(), nullable=True),
        sa.Column(
            "design_tokens",
            sa.JSON(),
            nullable=True,
            comment="Complete visual design: colors, typography, images, layout",
        ),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("output_dir", sa.String(length=500), nullable=True),
        sa.Column("pdf_path", sa.String(length=500), nullable=True),
        sa.Column("pdf_path_en", sa.String(length=500), nullable=True),
        sa.Column("phase_progress", sa.JSON(), nullable=True),
        sa.Column("creative_brief", sa.Text(), nullable=True),
        sa.Column("persona_id", sa.String(length=36), nullable=True),
        sa.Column("assigned_reviewer_id", sa.String(length=36), nullable=True),
        sa.Column("rubric_id", sa.String(length=36), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("current_phase", sa.String(length=50), nullable=True),
        sa.Column("phase_status", sa.String(length=50), nullable=True),
        sa.Column(
            "workflow_status", sa.String(length=50), server_default="", nullable=False
        ),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("creator_name", sa.String(length=100), nullable=True),
        sa.Column("creator_handle", sa.String(length=100), nullable=True),
        sa.Column("creator_avatar_url", sa.String(length=500), nullable=True),
        sa.Column("creator_website", sa.String(length=500), nullable=True),
        sa.Column("creator_asset_id", sa.String(length=36), nullable=True),
        sa.Column("presentation_policy_version", sa.String(length=64), nullable=True),
        sa.Column("presentation_policy_checksum", sa.String(length=80), nullable=True),
        sa.Column("artifact_version", sa.String(length=80), nullable=True),
        sa.Column("slide_layout_strategy", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_asset_id"], ["carousel_creator_assets.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["persona_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rubric_id"],
            ["quality_rubrics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_carousel_projects_created_at",
        "carousel_projects",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_carousel_projects_status", "carousel_projects", ["status"], unique=False
    )
    op.create_index(
        "idx_carousel_projects_updated_at",
        "carousel_projects",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_messages_conversation_id", "messages", ["conversation_id"], unique=False
    )
    op.create_index("idx_messages_created_at", "messages", ["created_at"], unique=False)
    op.create_table(
        "blog_posts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("excerpt", sa.String(length=500), nullable=True),
        sa.Column("featured_image_url", sa.String(length=500), nullable=True),
        sa.Column("author_id", sa.String(length=36), nullable=True),
        sa.Column("reviewer_id", sa.String(length=36), nullable=True),
        sa.Column("editor_comments", sa.JSON(), nullable=False),
        sa.Column("version_history", sa.JSON(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("citations", sa.JSON(), nullable=False),
        sa.Column("ai_suggestions", sa.JSON(), nullable=False),
        sa.Column("ai_generation_metadata", sa.JSON(), nullable=False),
        sa.Column("ai_disclosure_label", sa.String(length=50), nullable=True),
        sa.Column("meta_title", sa.String(length=255), nullable=True),
        sa.Column("meta_description", sa.String(length=500), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("canonical_url", sa.String(length=500), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("comment_count", sa.Integer(), nullable=False),
        sa.Column("share_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("submitted_for_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["carousel_projects.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("idx_blog_posts_author", "blog_posts", ["author_id"], unique=False)
    op.create_index(
        "idx_blog_posts_author_status_updated",
        "blog_posts",
        ["author_id", "status", "updated_at"],
        unique=False,
    )
    op.create_index(
        "idx_blog_posts_project", "blog_posts", ["project_id"], unique=False
    )
    op.create_index("idx_blog_posts_slug", "blog_posts", ["slug"], unique=False)
    op.create_index("idx_blog_posts_status", "blog_posts", ["status"], unique=False)
    op.create_table(
        "carousel_artifact_builds",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_version", sa.String(length=80), nullable=False),
        sa.Column("operation_id", sa.String(length=64), nullable=False),
        sa.Column("source_lock_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("staging_path", sa.String(length=500), nullable=True),
        sa.Column("error_json", sa.JSON(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["carousel_projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_carousel_artifact_builds_project",
        "carousel_artifact_builds",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "idx_carousel_artifact_builds_status",
        "carousel_artifact_builds",
        ["status"],
        unique=False,
    )
    op.create_table(
        "carousel_slides",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("slide_number", sa.Integer(), nullable=False),
        sa.Column("slide_type", sa.String(length=20), nullable=False),
        sa.Column("heading", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("html_content", sa.Text(), nullable=True),
        sa.Column("image_path", sa.String(length=500), nullable=True),
        sa.Column("image_prompt", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("extras", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["carousel_projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_carousel_slides_number",
        "carousel_slides",
        ["project_id", "slide_number"],
        unique=True,
    )
    op.create_index(
        "idx_carousel_slides_project_id",
        "carousel_slides",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "research_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("extracted_content", sa.Text(), nullable=True),
        sa.Column("relevance_score", sa.Integer(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["carousel_projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_research_sources_project_id",
        "research_sources",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "idx_research_sources_type", "research_sources", ["source_type"], unique=False
    )
    op.create_table(
        "carousel_image_generations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("slide_id", sa.String(length=36), nullable=False),
        sa.Column("slide_number", sa.Integer(), nullable=False),
        sa.Column("generation_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("output_path", sa.String(length=500), nullable=True),
        sa.Column("prompt_hash", sa.String(length=64), nullable=True),
        sa.Column("provider", sa.String(length=30), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("style", sa.String(length=64), nullable=True),
        sa.Column("raw_prompt", sa.Text(), nullable=True),
        sa.Column("rendered_prompt", sa.Text(), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.Column("provider_image_id", sa.String(length=128), nullable=True),
        sa.Column("error_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["carousel_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["slide_id"], ["carousel_slides.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("generation_key"),
    )
    op.create_index(
        "idx_carousel_image_generations_project",
        "carousel_image_generations",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "idx_carousel_image_generations_slide",
        "carousel_image_generations",
        ["slide_id"],
        unique=False,
    )
    op.create_index(
        "idx_carousel_image_generations_status",
        "carousel_image_generations",
        ["status"],
        unique=False,
    )
    op.create_table(
        "content_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("blog_post_id", sa.String(length=36), nullable=True),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("extracted_key_points", sa.JSON(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["blog_post_id"], ["blog_posts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["carousel_projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_content_sources_blog_post_id",
        "content_sources",
        ["blog_post_id"],
        unique=False,
    )
    op.create_index(
        "idx_content_sources_project_id",
        "content_sources",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "idx_content_sources_type", "content_sources", ["source_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_content_sources_type", table_name="content_sources")
    op.drop_index("idx_content_sources_project_id", table_name="content_sources")
    op.drop_index("idx_content_sources_blog_post_id", table_name="content_sources")
    op.drop_table("content_sources")
    op.drop_index(
        "idx_carousel_image_generations_status", table_name="carousel_image_generations"
    )
    op.drop_index(
        "idx_carousel_image_generations_slide", table_name="carousel_image_generations"
    )
    op.drop_index(
        "idx_carousel_image_generations_project",
        table_name="carousel_image_generations",
    )
    op.drop_table("carousel_image_generations")
    op.drop_index("idx_research_sources_type", table_name="research_sources")
    op.drop_index("idx_research_sources_project_id", table_name="research_sources")
    op.drop_table("research_sources")
    op.drop_index("idx_carousel_slides_project_id", table_name="carousel_slides")
    op.drop_index("idx_carousel_slides_number", table_name="carousel_slides")
    op.drop_table("carousel_slides")
    op.drop_index(
        "idx_carousel_artifact_builds_status", table_name="carousel_artifact_builds"
    )
    op.drop_index(
        "idx_carousel_artifact_builds_project", table_name="carousel_artifact_builds"
    )
    op.drop_table("carousel_artifact_builds")
    op.drop_index("idx_blog_posts_status", table_name="blog_posts")
    op.drop_index("idx_blog_posts_slug", table_name="blog_posts")
    op.drop_index("idx_blog_posts_project", table_name="blog_posts")
    op.drop_index("idx_blog_posts_author_status_updated", table_name="blog_posts")
    op.drop_index("idx_blog_posts_author", table_name="blog_posts")
    op.drop_table("blog_posts")
    op.drop_index("idx_messages_created_at", table_name="messages")
    op.drop_index("idx_messages_conversation_id", table_name="messages")
    op.drop_table("messages")
    op.drop_index("idx_carousel_projects_updated_at", table_name="carousel_projects")
    op.drop_index("idx_carousel_projects_status", table_name="carousel_projects")
    op.drop_index("idx_carousel_projects_created_at", table_name="carousel_projects")
    op.drop_table("carousel_projects")
    op.drop_index("idx_rubric_scores_rubric_id", table_name="rubric_evaluation_scores")
    op.drop_index(
        "idx_rubric_scores_content_type", table_name="rubric_evaluation_scores"
    )
    op.drop_index("idx_rubric_scores_content_id", table_name="rubric_evaluation_scores")
    op.drop_table("rubric_evaluation_scores")
    op.drop_index(
        "idx_persona_corrections_persona_id", table_name="persona_corrections"
    )
    op.drop_index(
        "idx_persona_corrections_created_at", table_name="persona_corrections"
    )
    op.drop_table("persona_corrections")
    op.drop_index("idx_documents_updated_at", table_name="documents")
    op.drop_index("idx_documents_status", table_name="documents")
    op.drop_index("idx_documents_owner_id", table_name="documents")
    op.drop_index("idx_documents_created_at", table_name="documents")
    op.drop_table("documents")
    op.drop_index("idx_conversations_updated_at", table_name="conversations")
    op.drop_index("idx_conversations_owner_id", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(
        "idx_carousel_creator_assets_owner", table_name="carousel_creator_assets"
    )
    op.drop_table("carousel_creator_assets")
    op.drop_index("idx_audit_event_type", table_name="workflow_audit_log")
    op.drop_index("idx_audit_created_at", table_name="workflow_audit_log")
    op.drop_index("idx_audit_aggregate", table_name="workflow_audit_log")
    op.drop_table("workflow_audit_log")
    op.drop_index("idx_users_role", table_name="users")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_quality_rubrics_name", table_name="quality_rubrics")
    op.drop_index("idx_quality_rubrics_is_default", table_name="quality_rubrics")
    op.drop_table("quality_rubrics")
    op.drop_index("idx_persona_profiles_version", table_name="persona_profiles")
    op.drop_index("idx_persona_profiles_name", table_name="persona_profiles")
    op.drop_table("persona_profiles")
    op.drop_index("idx_notifications_user_status", table_name="notifications")
    op.drop_index("idx_notifications_deadline", table_name="notifications")
    op.drop_index("idx_notifications_content", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("idx_editorial_comments_status", table_name="editorial_comments")
    op.drop_index("idx_editorial_comments_content_id", table_name="editorial_comments")
    op.drop_table("editorial_comments")
    op.drop_index("idx_content_versions_version", table_name="content_versions")
    op.drop_index("idx_content_versions_type", table_name="content_versions")
    op.drop_index("idx_content_versions_content_id", table_name="content_versions")
    op.drop_table("content_versions")
    op.drop_index("idx_content_locks_expires", table_name="content_locks")
    op.drop_index("idx_content_locks_content", table_name="content_locks")
    op.drop_table("content_locks")
    # ### end Alembic commands ###
