"""Constants for agent ticket tooling."""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
AGENT_DIR = REPO_ROOT / ".agent"
TASKS_DIR = AGENT_DIR / "tasks"
REPORTS_DIR = AGENT_DIR / "reports"
BOARD_PATH = AGENT_DIR / "BOARD.md"
CONFIG_PATH = AGENT_DIR / "config.yaml"

TICKET_PREFIX = "AE"
TEMPLATE_FULL = "_template.md"
TEMPLATE_HOTFIX = "_template.hotfix.md"

STATUS_INTAKE = "Intake"
STATUS_SHAPING = "Shaping"
STATUS_READY = "Ready"
STATUS_PLANNING = "Planning"
STATUS_IN_DEVELOPMENT = "In Development"
STATUS_DEV_COMPLETE = "Dev Complete"
STATUS_QA_RUNNING = "QA Running"
STATUS_NEEDS_FIXES = "Needs Fixes"
STATUS_BLOCKED = "Blocked"
STATUS_REVIEW = "Review"
STATUS_READY_TO_MERGE = "Ready to Merge"
STATUS_DONE = "Done"
STATUS_CANCELLED = "Cancelled"

ALL_STATUSES = (
    STATUS_INTAKE,
    STATUS_SHAPING,
    STATUS_READY,
    STATUS_PLANNING,
    STATUS_IN_DEVELOPMENT,
    STATUS_DEV_COMPLETE,
    STATUS_QA_RUNNING,
    STATUS_NEEDS_FIXES,
    STATUS_BLOCKED,
    STATUS_REVIEW,
    STATUS_READY_TO_MERGE,
    STATUS_DONE,
    STATUS_CANCELLED,
)

BOARD_COLUMNS = ALL_STATUSES

TIER_T0 = "T0"
TIER_T1 = "T1"
TIER_T2 = "T2"
TIER_T3 = "T3"

FIELD_STATUS = "Status"
FIELD_TIER = "Tier"

SECTION_ACCEPTANCE_CRITERIA = "## Acceptance Criteria"
SECTION_GOAL = "## Goal"
SECTION_PROBLEM = "## Problem"
SECTION_SCOPE = "## Scope"
SECTION_NON_GOALS = "## Non-Goals"
SECTION_QA_REPORT = "## QA Report"
SECTION_FINAL_SUMMARY = "## Final Summary"
SECTION_TEST_EVIDENCE = "## Test Evidence"

REQUIRED_READY_SECTIONS = (
    SECTION_GOAL,
    SECTION_PROBLEM,
    SECTION_SCOPE,
    SECTION_NON_GOALS,
    SECTION_ACCEPTANCE_CRITERIA,
)

HOTFIX_MIN_SECTIONS = (
    SECTION_GOAL,
    SECTION_PROBLEM,
    SECTION_SCOPE,
    SECTION_NON_GOALS,
    SECTION_ACCEPTANCE_CRITERIA,
)

REPORT_DEV_SUFFIX = ".dev-summary.md"
REPORT_QA_SUFFIX = ".qa.md"
