"""SSE constants for editorial workflow."""

from __future__ import annotations

from rag_backend.domain.constants.carousel_workflow import (
    WORKFLOW_ARTIFACT_TYPE_DESIGN_APPLIED,
    WORKFLOW_ARTIFACT_TYPE_IMAGE_ASSETS,
    WORKFLOW_ARTIFACT_TYPE_OUTLINE,
    WORKFLOW_ARTIFACT_TYPE_PERSONA_SCORES,
    WORKFLOW_ARTIFACT_TYPE_SLIDE_DRAFTS,
)

SSE_EVENT_PHASE_CHANGE = "phase_change"
SSE_EVENT_PROGRESS = "progress"
SSE_EVENT_REVIEW_REQUIRED = "review_required"
SSE_EVENT_ERROR = "error"
SSE_EVENT_ARTIFACT = "artifact"
SSE_EVENT_KEEPALIVE = "_keepalive"
WORKFLOW_SSE_KEEPALIVE_SECONDS = 30
WORKFLOW_SSE_MAX_SUBSCRIBERS_PER_PROJECT = 10
SSE_PAYLOAD_FIELD_EVENT = "event"
SSE_PAYLOAD_FIELD_GATE = "gate_payload"
SSE_PAYLOAD_FIELD_MESSAGE = "message"
SSE_PAYLOAD_FIELD_RECOVERABLE = "recoverable"

WORKFLOW_ARTIFACT_UPDATE_FIELD_MAP: dict[str, str] = {
    "outline": WORKFLOW_ARTIFACT_TYPE_OUTLINE,
    "slide_drafts": WORKFLOW_ARTIFACT_TYPE_SLIDE_DRAFTS,
    "design_applied": WORKFLOW_ARTIFACT_TYPE_DESIGN_APPLIED,
    "image_assets": WORKFLOW_ARTIFACT_TYPE_IMAGE_ASSETS,
    "persona_scores": WORKFLOW_ARTIFACT_TYPE_PERSONA_SCORES,
}

__all__ = [
    "SSE_EVENT_ARTIFACT",
    "SSE_EVENT_ERROR",
    "SSE_EVENT_KEEPALIVE",
    "SSE_EVENT_PHASE_CHANGE",
    "SSE_EVENT_PROGRESS",
    "SSE_EVENT_REVIEW_REQUIRED",
    "SSE_PAYLOAD_FIELD_EVENT",
    "SSE_PAYLOAD_FIELD_GATE",
    "SSE_PAYLOAD_FIELD_MESSAGE",
    "SSE_PAYLOAD_FIELD_RECOVERABLE",
    "WORKFLOW_ARTIFACT_UPDATE_FIELD_MAP",
    "WORKFLOW_SSE_KEEPALIVE_SECONDS",
    "WORKFLOW_SSE_MAX_SUBSCRIBERS_PER_PROJECT",
]
