"""Pydantic schemas for API requests and responses."""

# Common
# Carousel
from rag_backend.api.schemas.carousel import (
    CarouselBlogI18nResponse,
    CarouselBlogImageMapEntry,
    CarouselBlogResponse,
    CarouselBlogWithDesignResponse,
    CarouselCaptionResponse,
    CarouselDesignColors,
    CarouselDesignImages,
    CarouselDesignLayout,
    CarouselDesignResponse,
    CarouselDesignTypography,
    CarouselGenerateRequest,
    CarouselProjectCreate,
    CarouselProjectListResponse,
    CarouselProjectResponse,
    CarouselProjectUpdate,
    CarouselSlideResponse,
    CarouselStatusResponse,
    InstagramPublishRequest,
    InstagramPublishResponse,
    ResearchSourceResponse,
)

# Chat
from rag_backend.api.schemas.chat import (
    ChatMessageRequest,
    ChatRequest,
    ChatResponse,
    ChatStreamResponse,
    ConversationCreate,
    ConversationListResponse,
    ConversationResponse,
    ConversationUpdate,
    MessageListResponse,
    MessageResponse,
    MessageSource,
    SearchRequest,
    SearchResponse,
    SearchResultResponse,
)
from rag_backend.api.schemas.common import ErrorResponse, HealthCheckResponse, HealthResponse

# Documents
from rag_backend.api.schemas.documents import (
    DocumentBase,
    DocumentCreate,
    DocumentListResponse,
    DocumentProcessingStatus,
    DocumentResponse,
    DocumentUpdate,
    DocumentUploadResponse,
)

__all__ = [
    "CarouselBlogI18nResponse",
    "CarouselBlogImageMapEntry",
    "CarouselBlogResponse",
    "CarouselBlogWithDesignResponse",
    "CarouselCaptionResponse",
    "CarouselDesignColors",
    "CarouselDesignImages",
    "CarouselDesignLayout",
    "CarouselDesignResponse",
    "CarouselDesignTypography",
    "CarouselGenerateRequest",
    "CarouselProjectCreate",
    "CarouselProjectListResponse",
    "CarouselProjectResponse",
    "CarouselProjectUpdate",
    "CarouselSlideResponse",
    "CarouselStatusResponse",
    "ChatMessageRequest",
    "ChatRequest",
    "ChatResponse",
    "ChatStreamResponse",
    "ConversationCreate",
    "ConversationListResponse",
    "ConversationResponse",
    "ConversationUpdate",
    "DocumentBase",
    "DocumentCreate",
    "DocumentListResponse",
    "DocumentProcessingStatus",
    "DocumentResponse",
    "DocumentUpdate",
    "DocumentUploadResponse",
    "ErrorResponse",
    "HealthCheckResponse",
    "HealthResponse",
    "InstagramPublishRequest",
    "InstagramPublishResponse",
    "MessageListResponse",
    "MessageResponse",
    "MessageSource",
    "ResearchSourceResponse",
    "SearchRequest",
    "SearchResponse",
    "SearchResultResponse",
]
