"""Pydantic schemas for API requests and responses."""

# Common
# Carousel
# Blog Posts
from rag_backend.api.schemas.blog_post import (
    BlogPostCreate,
    BlogPostListResponse,
    BlogPostResponse,
    BlogPostUpdate,
    BlogPostVersionResponse,
    ContentSourceCreate,
    ContentSourceListResponse,
    ContentSourceResponse,
    ContentVersionResponse,
    EditorialCommentCreate,
    EditorialCommentListResponse,
    EditorialCommentResponse,
)
from rag_backend.api.schemas.carousel import (
    CarouselBlogI18nResponse,
    CarouselBlogImageMapEntry,
    CarouselBlogResponse,
    CarouselBlogWithDesignResponse,
    CarouselCaptionResponse,
    CarouselDesignColors,
    CarouselDesignImages,
    CarouselDesignLayout,
    CarouselDesignResponse,
    CarouselDesignTypography,
    CarouselProjectCreate,
    CarouselProjectListResponse,
    CarouselProjectResponse,
    CarouselProjectUpdate,
    CarouselSlideResponse,
    InstagramPublishRequest,
    InstagramPublishResponse,
    ResearchSourceResponse,
)

# Chat
from rag_backend.api.schemas.chat import (
    ChatMessageRequest,
    ChatRequest,
    ChatResponse,
    ChatStreamResponse,
    ConversationCreate,
    ConversationListResponse,
    ConversationResponse,
    ConversationUpdate,
    MessageListResponse,
    MessageResponse,
    MessageSource,
    SearchRequest,
    SearchResponse,
    SearchResultResponse,
)
from rag_backend.api.schemas.common import (
    ErrorResponse,
    HealthCheckResponse,
    HealthResponse,
)

# Documents
from rag_backend.api.schemas.documents import (
    DocumentBase,
    DocumentCreate,
    DocumentListResponse,
    DocumentProcessingStatus,
    DocumentResponse,
    DocumentUpdate,
    DocumentUploadResponse,
)

# Persona & Rubric
from rag_backend.api.schemas.persona_rubric import (
    PersonaProfileCreate,
    PersonaProfileListResponse,
    PersonaProfileResponse,
    PersonaProfileUpdate,
    QualityRubricCreate,
    QualityRubricListResponse,
    QualityRubricResponse,
    QualityRubricUpdate,
    RubricCriterion,
    RubricEvaluationResponse,
    RubricEvaluationScore,
    ToneAttributes,
)

__all__ = [
    "BlogPostCreate",
    "BlogPostListResponse",
    "BlogPostResponse",
    "BlogPostUpdate",
    "BlogPostVersionResponse",
    "CarouselBlogI18nResponse",
    "CarouselBlogImageMapEntry",
    "CarouselBlogResponse",
    "CarouselBlogWithDesignResponse",
    "CarouselCaptionResponse",
    "CarouselDesignColors",
    "CarouselDesignImages",
    "CarouselDesignLayout",
    "CarouselDesignResponse",
    "CarouselDesignTypography",
    "CarouselProjectCreate",
    "CarouselProjectListResponse",
    "CarouselProjectResponse",
    "CarouselProjectUpdate",
    "CarouselSlideResponse",
    "ChatMessageRequest",
    "ChatRequest",
    "ChatResponse",
    "ChatStreamResponse",
    "ContentSourceCreate",
    "ContentSourceListResponse",
    "ContentSourceResponse",
    "ContentVersionResponse",
    "ConversationCreate",
    "ConversationListResponse",
    "ConversationResponse",
    "ConversationUpdate",
    "DocumentBase",
    "DocumentCreate",
    "DocumentListResponse",
    "DocumentProcessingStatus",
    "DocumentResponse",
    "DocumentUpdate",
    "DocumentUploadResponse",
    "EditorialCommentCreate",
    "EditorialCommentListResponse",
    "EditorialCommentResponse",
    "ErrorResponse",
    "HealthCheckResponse",
    "HealthResponse",
    "InstagramPublishRequest",
    "InstagramPublishResponse",
    "MessageListResponse",
    "MessageResponse",
    "MessageSource",
    "PersonaProfileCreate",
    "PersonaProfileListResponse",
    "PersonaProfileResponse",
    "PersonaProfileUpdate",
    "QualityRubricCreate",
    "QualityRubricListResponse",
    "QualityRubricResponse",
    "QualityRubricUpdate",
    "ResearchSourceResponse",
    "RubricCriterion",
    "RubricEvaluationResponse",
    "RubricEvaluationScore",
    "SearchRequest",
    "SearchResponse",
    "SearchResultResponse",
    "ToneAttributes",
]
