#!/usr/bin/env python3
"""Architecture-violation baseline for the modularization plan (AE-0078).

Measurement only — changes nothing. Scans backend/src/rag_backend with
stdlib regex (same signal Import Linter would see if its wildcards were
removed) and prints a sorted, timestamp-free report so repeated runs are
byte-identical.

Categories:
  wildcard-hidden (declared forbidden, exempted in .importlinter):
    application -> infrastructure, application -> agents
  target-forbidden (allowed or uncovered today, forbidden post-move):
    agents -> application, api -> infrastructure
  service-locator: get_container( outside bootstrap/ + api/dependencies/
  repo-commit: .commit( inside infrastructure/database adapters
"""

from __future__ import annotations

import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "backend" / "src" / "rag_backend"

IMPORT_RE = re.compile(
    r"^\s*(?:from\s+(rag_backend\.[\w.]+)\s+import\s+(.+)|import\s+(rag_backend\.[\w.]+))",
)

CATEGORIES = [
    ("application -> infrastructure", "application", "rag_backend.infrastructure", "wildcard-hidden"),
    ("application -> agents", "application", "rag_backend.agents", "wildcard-hidden"),
    ("agents -> application", "agents", "rag_backend.application", "target-forbidden (no contract today)"),
    ("api -> infrastructure", "api", "rag_backend.infrastructure", "target-forbidden (allowed by contract 4)"),
]

# Composition-root paths allowed to resolve the DI container (AE-0080):
# bootstrap/ is the relocated composition root (ADR-0009 §9); api/dependencies/
# holds the request-scoped DI providers at the HTTP edge. The old api/app.py is
# now a thin re-export shim and no longer holds composition-root wiring.
CONTAINER_ALLOWED = ("bootstrap/", "api/dependencies/")


def module_of(path: Path) -> str:
    rel = path.relative_to(ROOT.parent)
    return str(rel.with_suffix("")).replace("/", ".").removesuffix(".__init__")


TYPE_CHECKING_RE = re.compile(r"^(\s*)if\s+(typing\.)?TYPE_CHECKING\b")


def scan_category(src_pkg: str, target_prefix: str):
    """Collect import pairs; TYPE_CHECKING-guarded ones are tagged apart.

    Import Linter also counts TYPE_CHECKING imports by default, so they
    stay in the totals for parity — but they are zero-cost at runtime,
    so ratchet planning gets them as a separate list.
    """
    pairs: list[tuple[str, str]] = []
    tc_pairs: list[tuple[str, str]] = []
    symbols: Counter[str] = Counter()
    for f in sorted((ROOT / src_pkg).rglob("*.py")):
        tc_indent: int | None = None
        for line in f.read_text().splitlines():
            stripped = line.strip()
            tc_match = TYPE_CHECKING_RE.match(line)
            if tc_match:
                tc_indent = len(tc_match.group(1))
                continue
            if tc_indent is not None and stripped:
                indent = len(line) - len(line.lstrip())
                if indent <= tc_indent:
                    tc_indent = None
            m = IMPORT_RE.match(line)
            if not m:
                continue
            target = m.group(1) or m.group(3)
            if not target or not target.startswith(target_prefix):
                continue
            bucket = tc_pairs if tc_indent is not None else pairs
            bucket.append((module_of(f), target))
            if m.group(2):
                for sym in m.group(2).split(","):
                    sym = sym.strip().split(" as ")[0].strip("() ")
                    if sym:
                        symbols[f"{target}.{sym}"] += 1
    return pairs, tc_pairs, symbols


def scan_pattern(base: Path, pattern: str, allowed: tuple[str, ...] = ()):
    hits = []
    rx = re.compile(pattern)
    for f in sorted(base.rglob("*.py")):
        rel = str(f.relative_to(ROOT))
        if any(rel.startswith(a) or a in rel for a in allowed):
            continue
        for i, line in enumerate(f.read_text().splitlines(), 1):
            if rx.search(line):
                hits.append(f"{module_of(f)}:{i}")
    return hits


def main() -> int:
    out = []
    appendix: list[str] = []
    out.append("# Import-violation baseline (generated by scripts/metrics/import_baseline.py)")
    for title, src, target, klass in CATEGORIES:
        pairs, tc_pairs, symbols = scan_category(src, target)
        unique = sorted(set(pairs))
        tc_unique = sorted(set(tc_pairs) - set(pairs))
        out.append(f"\n## {title}  [{klass}]")
        out.append(
            f"import-lines={len(pairs) + len(tc_pairs)} "
            f"(runtime={len(pairs)}, type-checking-only={len(tc_pairs)}) "
            f"unique-module-pairs={len(unique) + len(tc_unique)}"
        )
        out.extend(f"- {a} -> {b}" for a, b in unique)
        out.extend(f"- {a} -> {b}  [type-checking-only]" for a, b in tc_unique)
        top = symbols.most_common(20)
        if top:
            out.append("top imported symbols (de-facto public contract):")
            out.extend(f"  {n:3d}x {s}" for s, n in top)
        appendix.extend(f"{a} -> {b}" for a, b in unique)
        appendix.extend(f"{a} -> {b}  # type-checking-only" for a, b in tc_unique)

    locator = scan_pattern(ROOT, r"get_container\(", CONTAINER_ALLOWED)
    out.append(f"\n## get_container() outside bootstrap-eligible code\ncount={len(locator)}")
    out.extend(f"- {h}" for h in locator)

    commits = scan_pattern(ROOT / "infrastructure" / "database", r"\.commit\(")
    out.append(f"\n## .commit() inside infrastructure/database adapters\ncount={len(commits)}")
    out.extend(f"- {h}" for h in commits)

    out.append("\n## Machine-readable appendix (one `module -> module` pair per line)")
    out.append("```text")
    out.extend(sorted(set(appendix)))
    out.append("```")
    sys.stdout.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
