import {
  BG_CARD as DASHBOARD_CHAT_BG_CARD,
  BG_DEEP as DASHBOARD_CHAT_BG_DEEP,
  BG_ELEVATED as DASHBOARD_CHAT_BG_ELEVATED,
  NEON_AMBER as DASHBOARD_CHAT_AMBER,
  NEON_AMBER_DIM as DASHBOARD_CHAT_AMBER_DIM,
  NEON_BG_HEADER as DASHBOARD_CHAT_BG_HEADER,
  NEON_BG_INPUT_BAR as DASHBOARD_CHAT_BG_INPUT_BAR,
  NEON_BG_INPUT_DARK as DASHBOARD_CHAT_BG_INPUT_DARK,
  NEON_BG_INPUT_DARKER as DASHBOARD_CHAT_BG_INPUT_DARKER,
  NEON_BG_OVERLAY as DASHBOARD_CHAT_BG_OVERLAY,
  NEON_BG_OVERLAY_LIGHT as DASHBOARD_CHAT_BG_OVERLAY_LIGHT,
  NEON_BORDER_LIGHT as DASHBOARD_CHAT_BORDER_LIGHT,
  NEON_BORDER_MEDIUM as DASHBOARD_CHAT_BORDER_MEDIUM,
  NEON_BORDER_STRONG as DASHBOARD_CHAT_BORDER_STRONG,
  NEON_BORDER_SUBTLE as DASHBOARD_CHAT_BORDER_SUBTLE,
  NEON_CYAN as DASHBOARD_CHAT_CYAN,
  NEON_CYAN_DIM as DASHBOARD_CHAT_CYAN_DIM,
  NEON_MAGENTA as DASHBOARD_CHAT_MAGENTA,
  NEON_MAGENTA_DIM as DASHBOARD_CHAT_MAGENTA_DIM,
  NEON_TEAL as DASHBOARD_CHAT_TEAL,
  NEON_TEAL_DIM as DASHBOARD_CHAT_TEAL_DIM,
  NEON_CARD_BORDER as DASHBOARD_CHAT_CARD_BORDER,
  TEXT as DASHBOARD_CHAT_TEXT,
  TEXT_DIM as DASHBOARD_CHAT_TEXT_DIM,
  TEXT_MUTED as DASHBOARD_CHAT_TEXT_MUTED,
} from "@/constants/neon";

export {
  DASHBOARD_CHAT_BG_CARD,
  DASHBOARD_CHAT_BG_DEEP,
  DASHBOARD_CHAT_BG_ELEVATED,
  DASHBOARD_CHAT_AMBER,
  DASHBOARD_CHAT_AMBER_DIM,
  DASHBOARD_CHAT_BG_HEADER,
  DASHBOARD_CHAT_BG_INPUT_BAR,
  DASHBOARD_CHAT_BG_INPUT_DARK,
  DASHBOARD_CHAT_BG_INPUT_DARKER,
  DASHBOARD_CHAT_BG_OVERLAY,
  DASHBOARD_CHAT_BG_OVERLAY_LIGHT,
  DASHBOARD_CHAT_BORDER_LIGHT,
  DASHBOARD_CHAT_BORDER_MEDIUM,
  DASHBOARD_CHAT_BORDER_STRONG,
  DASHBOARD_CHAT_BORDER_SUBTLE,
  DASHBOARD_CHAT_CYAN,
  DASHBOARD_CHAT_CYAN_DIM,
  DASHBOARD_CHAT_MAGENTA,
  DASHBOARD_CHAT_MAGENTA_DIM,
  DASHBOARD_CHAT_TEAL,
  DASHBOARD_CHAT_TEAL_DIM,
  DASHBOARD_CHAT_CARD_BORDER,
  DASHBOARD_CHAT_TEXT,
  DASHBOARD_CHAT_TEXT_DIM,
  DASHBOARD_CHAT_TEXT_MUTED,
};

export const DASHBOARD_CHAT_MONO_FONT =
  "'JetBrains Mono', ui-monospace, monospace";

export const DASHBOARD_CHAT_TYPING_LABEL = "Analyzing tone alignment...";

export const DASHBOARD_CHAT_ASSISTANT_INTRO =
  "Hello Pedro. I'm your Alter-Ego assistant. I have access to your knowledge graph, carousel pipeline, and blog archive. How can I help you today?";

export const DASHBOARD_CHAT_USER_PROMPT =
  "Can you review the DeepSeek V4 carousel draft and check if the market positioning aligns with the competitive analysis we did last week?";

export const DASHBOARD_CHAT_ASSISTANT_REPLY =
  "I've cross-referenced the carousel with the competitive analysis from last week. A few observations:\n\n1. The price comparison slide ($3.50 vs $25) is accurate and well-contextualized.\n2. The benchmark data (93.5% LiveCodeBench) matches our latest evaluation run.\n3. Consider adding a note about the Huawei Ascend chip compatibility, which was a key differentiator in our analysis.";

export const DASHBOARD_CHAT_USER_FOLLOW_UP =
  "Good catch. I'll add the Huawei chip detail. Can you also check the tone for the technical audience slide?";
